### ISSUE TITLE
Keep sqlite db out of git

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#108]
currently whenever someone runs polaris locally, they'll modify the db.sqlite3 file which creates a change in git.  We need to make sure that this is not the case otherwise people will be checking in miscellaneous changes in their PRs

**Comment by JakeUrban** [comment]
The problem with keeping the db.sqlite3 file out of git is that if we want our data to persist when containers are destroyed, the db.sqlite3 file needs to exist on the host machine, so docker-compose can mount a volume on it.

If we add db.sqlite3 to .gitignore, the developer will have to create the file before running `docker-compose build`. This is likely what will have to happen to fix this issue.
