### ISSUE TITLE
Add multisig support to stellar_sdk

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#109]
Creating an issue for sprint tracking. There is already an [issue](https://github.com/StellarCN/py-stellar-base/issues/252) on the py-stellar-base repository.

**Comment by overcat** [comment]
stellar-sdk 2.1.1-beta1 has been published, please let me know if you have any questions.
- [Github Release](https://github.com/StellarCN/py-stellar-base/releases/tag/2.1.1-beta1)
- [PyPi Release](https://pypi.org/project/stellar-sdk/2.1.1b1/)
- [Document](https://stellar-sdk.readthedocs.io/en/2.1.1-beta1/api.html#sep-0010-stellar-web-authentication)
- [Code Example](https://github.com/StellarCN/py-stellar-base/blob/2.1.1-beta1/examples/transaction_challenge.py)
