### ISSUE TITLE
Float withdraw values seems to never resolve

### ISSUE THREAD

**Issue by tyvdh** [stellar/django-polaris#122]
Entered a withdraw value of 98.9, submitted, Stellar transaction successfully submitted, loop stuck infinitely checking with status `pending_user_transfer_start`.

Here are the logs from http://sep24.stellar.org/#HOME_DOMAIN=%22stellar-anchor-server.herokuapp.com%22
http://tyler.link/AJ67Mg

**Comment by JakeUrban** [comment]
You're on a roll, thanks for catching this. This bug can be traced back to when we changed amounts from `float` primitives to `decimal.Decimal` objects. The transaction matching function was still using float(amount). This will also be fixed in the next release :)
