### ISSUE TITLE
Check trustlines - asset issuer and limit

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#127]
If the account has multiple balances for the same asset code (multiple issuers), maybe the below code should check the issuer and balance limit as well.
https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/check_trustlines.py#L79

It's not usual to have two assets with the same code and the worst case scenario for the above code is running the deposit multiple times. It's not really a bug I think, just an idea for improvement. I think it's not necessary so feel free to close this issue.

See https://github.com/stellar/django-polaris/pull/126

**Comment by JakeUrban** [comment]
I agree we should check the issuer, but I don't think we should prevent the transaction from going through based on the limit. If the limit is less than what the new balance would be, I think it makes more sense to fail in `create_stellar_deposit`, which will save the appropriate error message on the transaction, which would help with debugging.
