### ISSUE TITLE
Withdraw enabled check issue

### ISSUE THREAD

**Issue by nikita-gorodeckij** [stellar/django-polaris#128]
I'm explore django-polaris and don't undestand why you use different `enabled` validation for withdraw and deposit.

In deposit you only check asset object from database and it works for me, but in withdraw view you also check `settings.ASSETS` dictionary.

It is problem for me, because I'm trying add asset with lower cased code but in `settings.ASSETS` it stores in uppercase and withdraw view always fails with: `unsupported asset type: xxx`

**Comment by JakeUrban** [comment]
We check `settings.ASSETS` in `def withdraw` because we need to retrieve the distribution address for the Transaction's creation. We don't need the distribution address in deposit transactions.

Thanks for pointing this out though. I'll change the check in `def withdraw` to:
```
elif asset.code.upper() not in settings.ASSETS:
```
