### ISSUE TITLE
Allow per-page scripts integration

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#134]
We have a script we use in our email confirmation form page to reload the page when you focus it (return to the app after confirming email).  Currently we're using [the title of the html page](https://github.com/stellar/django-polaris/pull/132/files#diff-b3845ebdab78f3325c727162cf116d73R334) to determine when to run the script, but a cleaner way would be to only inject that script to the page where its needed.

One possible solution would be to have the `scripts()` integration take a page key, and have the Dict returned by `content_for_transaction` return a page_key that `scripts(page_key)` can use to determine which scripts to attach

**Comment by JakeUrban** [comment]
I like the idea but I'm hesitant to add another explicitly defined key to `content_for_transaction()`. What do you think about passing the entire dict to `scripts()` instead a particular key value? That way, the scripts integration function could tailor the scripts returned based on the form or any extra keys the developer decides to return.

**Comment by msfeldstein** [comment]
i like that idea.
