### ISSUE TITLE
Withdrawal endpoint seems to differ from SEP-24 spec

### ISSUE THREAD

**Issue by andywer** [stellar/django-polaris#149]
### What version are you using?

The one currently deployed at testanchor.stellar.org.

### What did you do?

POST to `/transactions/withdraw/interactive`, follow the URL in the `interactive_customer_info_needed` response, complete the interactive flow.

In the meantime, polling the transaction status. Once it changes to `pending_user_transfer`, POST to `/transactions/withdraw/interactive` again as the spec says:

> 1. Success: no additional information needed
> Response code: 200 OK
> This is the correct response if the anchor is able to execute the withdrawal and needs no additional information about the user. **It should also be used if the anchor requires information about the user, but the information has previously been submitted and accepted.**

See [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#1-success-no-additional-information-needed).

### What did you expect to see?

Expected to see a `1. Success: no additional information needed` response.

### What did you see instead?

Saw another `interactive_customer_info_needed` response.

It is possible that the implementation is fine, but the spec is faulty or ambiguous.

**Comment by JakeUrban** [comment]
@msfeldstein now that the `/interactive` endpoint is no longer a `GET` request, I don't think we should have a [success response](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#1-success-no-additional-information-needed) since this goes against the idea that `POST` requests should be non-idempotent.

**Comment by msfeldstein** [comment]
> Requests to POST /interactive should always create a new transaction.

That's definitely the intention.  We should definitely clarify that in the SEP.  Im not sure if we should return the success response.  It seems like we'll always need more info, even if its just amount right?

**Comment by JakeUrban** [comment]
I agree. I'll create an issue in the stellar-protocol repo.
