### ISSUE TITLE
Feature Request: form initialization parameters in integrations.py

### ISSUE THREAD

**Issue by ronaldoy** [stellar/django-polaris#150]
### What problem does your feature solve?
Some forms require parameters for the _init_ section. Currently, there is no way to pass them using the return function in integrations.py. 

### What would you like to see?
Possibility to pass arguments in the "form" section of the "return" function (integrations.py) so the form can be initialized. For example, in Django it is possible to reference a form as SampleForm(param1=var1) and use var1 during the init. Any structure where we can replicate this behavior would solve the problem.

**Comment by JakeUrban** [comment]
Originally, I wanted to find a solution that would allow anchor's to initialize the form themselves inside `content_for_transaction()`, but this would require anchor's to perform logic currently handled by Polaris: initializing the form with URL or POST body arguments passed in the request.

This includes the optional `amount` argument used to pre-populate a form and also the data submitted via a previously rendered form. `amount` should also only be used to initialize the form when it is a `TransactionForm`, further complicating the logic every anchor would have to implement.

Instead, I believe the best approach is to return the form and it's initialization parameters as a tuple. Polaris would still handle the logic described above _and_ initialize the form with any key-value pairs passed in the arguments dictionary:
```
def content_for_transaction(transaction):
    return {
        "form": (MyForm, {"arg1": "val1"}),
    }
```
Polaris would then initialize the form with the argument dictionary like so:
```
content = rdi.content_for_transaction(transaction)
if content.get("form"):
    form_class, args = content["form"]
    content["form"] = form_class(**args)
```
This would get the job done but it makes the return type of `content_for_transaction()` more complex.
