### ISSUE TITLE
Design: KYC Customization API

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#16]
We need to create a KYC system that will allow anchors to customize the KYC pages with both their own branding and field definitions.  We should ensure anchors can get any type of information they might need, including text, dates, photos (id), etc.

This task is to design what the API will look like for that and get feedback from SDF and anchors.

**Comment by JakeUrban** [comment]
I'm going to split up the work needed here. We'll have separate design/implementation issues for Form Integrations (using custom forms), and then a design for supporting KYC flows that will use those integrations.

**Comment by JakeUrban** [comment]
Form Integrations: #20

**Comment by JakeUrban** [comment]
[Design](https://docs.google.com/document/d/1R_Jzt8-TkBfWsrMRwfKaLpaoW-hhaCqm6eS1NkftEqY/edit#)
