### ISSUE TITLE
Feature Request: Add fee information to the interactive flow

### ISSUE THREAD

**Issue by vitchor** [stellar/django-polaris#165]
Show how many SRTs the user will actually receive (taking into account the fees) in the deposit and withdraw amount screens.

**Comment by JakeUrban** [comment]
I have the functionality implemented, but where should the fee information be displayed?
![Screen Shot 2020-05-14 at 9 56 32 AM](https://user-images.githubusercontent.com/10968980/81962938-4c57a980-95c9-11ea-8117-1e26f4d15e76.png)

Under the submit button? What should the color and font size be of the text?

**Comment by JakeUrban** [comment]
I create a separate page that displays this information, like a "confirm" page where they see the amount in, fee, and amount out.
