### ISSUE TITLE
Design: Authentication for interactive flows

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#17]
We don't recommend keeping a long-lived jwt in the url of an interactive flow anymore so we should illustrate a best practice for how to return a url with a one-time-token and handle authentication on the backend properly

info here: https://github.com/stellar/stellar-protocol/pull/459/files

**Comment by JakeUrban** [comment]
Linking the [discussion](https://github.com/stellar/stellar-protocol/pull/459) on stellar-protocol
