### ISSUE TITLE
Feature Request: support multiple distribution accounts

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#21]
Currently there's support for only one anchor distribution account, but anchors might have multiple distribution accounts.  
The `create_stellar_deposit` command, for example, should have a parameter for specifying which distribution account to use.

**Comment by JakeUrban** [comment]
Thanks for filing, I agree Polaris should definitely provide support for this use case. There are a couple things we're focusing on first but I'll comment on this issue when I start working on it.

**Comment by JakeUrban** [comment]
@yuriescl full multi-asset support for Polaris has been implemented and will be released soon. PR: #80
