### ISSUE TITLE
Add instructions to run example

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#221]
There's no instructions in the readme for how to run the example server.  Someone in keybase didn't realize they need to set up the .env file, and im not sure what other steps needed to be taken but we should have some clear instructions to get up and running with the example.

**Comment by JakeUrban** [comment]
I agree there's almost no support for people who want to contribute to polaris or run the example. Most of the documentation is focused on those installing the `django-polaris` package.
