### ISSUE TITLE
Add tests for Polaris integrations

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#228]
We have unit tests of Polaris, but it would be nice if you could run a test suite that verified your integration functions and app behavior are functional and inline with the SEP.

Polaris could ship with a CLI tool, `check_integrations` that could be run using the `manage.py` script django provides.
```
python manage.py check_integrations
```

This would run a test suite (not using any framework, its unneeded) that ensures that all integrations implemented (or not) by the anchor work as expected. Some integrations are not testable (`content_for_transaction()`, `after_form_validiation()`) because they are not easily automate-able, but we can test those that are. 

The output would be a report on the state of the anchors integrations, similar to what pytest gives you after a test run.

This would be a multi-day effort so I need to determine if its worth it. After all, the developer can simply test their Polaris anchor with our demo client and validation suite. However this would help the anchor test their integrations without leaving the project, and without having to run the service.

**Comment by JakeUrban** [comment]
@ronaldoy Is this something you'd be interested in? Or is it unneeded considering with have anchor-validator.stellar.org?

**Comment by ronaldoy** [comment]
@JakeUrban It is not necessary considering the anchor validator.
