### ISSUE TITLE
SEP-10 not HTTP compliant

### ISSUE THREAD

**Issue by shredding** [stellar/django-polaris#252]
This does not work well with W3s recommendation of always adding a charset: https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep10/views.py#L186-L193

See: https://www.w3.org/International/articles/http-charset/index.en#charset

e.g. `application/json, charset: utf-8` breaks, hence client libraries that follow best practises needs to be hacked.

I'm not sure why that decision was made, but unless there are very good reasons not to do so DRF ships with HTTP-compliant Content Negotation out of the box, and just adding

```
parser_classes = [FormParser, JSONParser]
```

to the APIView would allow to get rid of the entire self-written content negotatiation.

**Comment by JakeUrban** [comment]
I agree, good catch. It will be fixed in the next release.
