### ISSUE TITLE
Include SEP-31 transactions in query for last received TX

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#254]
The management command `watch_transactions` is a stream of transactions in real time, correct?
If the server running Polaris gets shut down and some transactions occur while it's down, is it possible that some transactions are missed?
Ex: anchor receives Stellar payment but transaction status does not change because `watch_transactions` was not running

**Comment by JakeUrban** [comment]
Nope. If you look at [this section of the code](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/watch_transactions.py#L67) you'll see that Polaris begins streaming from the last successfully processed withdrawal transaction.

I'm just noticing now that we need to change the query to include SEP-31 transactions as well. I'm going to change this issue to address that.

**Comment by JakeUrban** [comment]
One thing to note about this though @yuriescl is that when the testnet resets, this breaks since the paging tokens testnet network reset. This means the anchor has to update the most recently completed TX's `paging_token` to `None` so the `watch_transactions` begins streaming from the present.

**Comment by yuriescl** [comment]
@JakeUrban Thanks.

Are these managament commands suitable for being managed by supervisord - can they get terminated gracefully?

**Comment by JakeUrban** [comment]
@yuriescl we use Heroku for testanchor.stellar.org which manages the processes for us, but you can use `supervisorctl`. However I haven't made changes to make sure exiting is "graceful", that'll be part of #244
