### ISSUE TITLE
Need Deposit Instructions Integration

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#26]
Currently there is no way for an anchor to display deposit instructions information.  In the deposit flow, after entering the amount, we jump straight to the 'receipt' page, and our only deposit steps are our custom 'Admin: Confirm Deposit' button, but real anchors need to be able to show concrete and varied instructions. nTokens deposit screen is shown below.

I think when the Transaction type is deposit and the status is `pending_user_transfer_start`, we should have more_info_url return a screen similar to below, and create an integration where the anchor can return arbitrary text or html to fit in the gray box with the instructions for how to deposit.

<img width="299" alt="Screen Shot 2019-12-03 at 2 26 08 PM" src="https://user-images.githubusercontent.com/161135/70078049-dd583c80-15b6-11ea-84e4-7e06730b982f.png">

For our staging infrastructure we can move the 'Admin: confirm deposit' button onto this page below the gray box instead of the receipt page.

**Comment by JakeUrban** [comment]
No need to add the "Confirm Deposit" button since we poll pending deposits now. But I agree with the suggestions made here. We'll have `/more_info` for `pending_user_transfer_start` transactions return something like this.

**Comment by JakeUrban** [comment]
PR: #41
