### ISSUE TITLE
Support Multi-sig Assets

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#289]
`Asset` holds a `distribution_seed` which is used to derive the pubkey, and the pubkey is used by responses and for watching transactions.
This makes it difficult for the Anchor if it wants to have a separate account just for receiving the payments (this would not require Polaris to know the private key).
Some Anchors have multiple distribution accounts and might not want to store all private keys in the server for security purposes.

Two questions:
- Is it currently possible to have multiple distribution accounts setup in Polaris?
- Is it currently possible to setup multi-sig distribution accounts in Polaris, in a way that it would allow an external service to add signatures to a transaction and allow it to proceed?

Both scenarios described above might be possible but I'm not sure if it would be worth to workaround the current Polaris instead of having it natively supported by Polaris.

**Comment by JakeUrban** [comment]
Heres how I'm thinking about a potential solution:

A polling-approach where clients go through a SEP-10ish dance to authenticate with and poll a custom Polaris SEP-24 endpoint could work. If proven to be useful and effective, this dance could be added to the SEP-24/SEP-10 spec. Specifically, this flow would benefit from a `pending_signatures` external SEP-24 status.

Here is what that flow might look like without the `pending_signatures` status:

1. A deposit is been received off-chain and the internal transaction record is found
2. Polaris will check if the transaction requires more than one signature based on the `signers` object on the distribution account of transaction's asset
    - These objects will likely be pulled from Horizon on application startup
3. If additional signatures are required, the transaction's external status is set to `pending_external`, a new Polaris `Transaction.pending_signatures` column is set to `True`, and a serialized `TransactionEnvelope` is saved to a new Polaris' `Transaction.envelope` column
4. Client applications in possession of a secret key for one of the distribution account's signers can authenticate with the Polaris service by going through a modified SEP-10 flow using the `GET /signers/auth?account=<account>` endpoint to receive a challenge transaction for the distribution `account`.
5. If the signature on the challenge sent back to the anchor via `POST /signers/auth` endpoint is from a signer of the distribution account, a SEP-10 JWT token should be returned by the anchor
6. The client can then use the SEP-10 JWT token to make requests to a `GET /signers/transactions` endpoint to get the `Transaction.envelope` XDRs that require the client's signature. 
7. These envelopes can be signed and `POSTed` back to the `/signers/transactions` endpoint. 
8. Once a transaction has enough signatures Polaris will change the status to `pending_anchor` and submit the transaction on the Stellar network

**Comment by JakeUrban** [comment]
@tomerweller @yuriescl

**Comment by yuriescl** [comment]
Looks good, ty

**Comment by JakeUrban** [comment]
After conversation with Tomer, Polaris will not mention the flow above. Instead, Polaris needs to support a flow as described:

1. The user has deposited the requested amount with the anchor off-chain
2. The anchor has detected the transfer in `DepositIntegration.poll_pending_deposits()`

At this point, the anchor _could_ signal to Polaris per-transaction whether or not more signatures need to be collected. This could be done via a new `Transaction` column value, like `Transaction.pending_signatures = True`.

With this design, Polaris would iterate over the `Transaction` objects returned from `poll_pending_deposits()` and put the them in the `pending_anchor` status as usual. However `Transaction` objects that are pending signatures will be _excluded_ in the query for `Transaction` objects ready to be submitted to Stellar.

Anchors would be expected to _define their own process for collecting signatures on a transaction_. `Transaction.envelope` may be added to the model to make it easier for anchors to maintain a WIP envelope.

It would also be much easier for anchors if SEP-24 had a `pending_signatures` status that signers of a distribution account could detect using the standardized interface. CC @tomerweller

**Comment by tomerweller** [comment]
Not sure about adding a `pending_signatures` status. 

Waiting for signatures is part of the internal processing on the anchor side so it should fit within the `pending_anchor`. No?

**Comment by JakeUrban** [comment]
It can work, thats what my current implementation does, but it makes it harder for signatures to be collected. Otherwise clients don't have a standard way of detecting if a transaction's envelope needs to be signed. 

Anchors will either notify the signers of the transaction (push model) or the anchor exposes the information that indicates which transactions need signatures (pull/poll model). A low hanging fruit is adding this status to better support the polling solution.

**Comment by tomerweller** [comment]
This sounds like a leaky abstraction. Is there any reason for the signer service integration interface to depend on the wallet facing transaction resource? 

P.S, 
why do we keep using signer**s** in plural? I don't think we should be aggregating signatures - that can lead to a stateful mess. If there are multiple signers we can let the external signer service take care of it - no need for polaris to be aware of it.

**Comment by JakeUrban** [comment]
There is no reason.

Regarding the P.S., I agree Polaris shouldn't be opinionated about the system that collects signatures and that an external system should do it. My draft PR currently adds a `Transaction.envelope` column and a `create_transaction_envelope()` utility function which should allow for other services to query for the envelope XDR and update the column value on each signature collected.

**Comment by tomerweller** [comment]
> should allow for other services to query for the envelope XDR and update the column value on each signature collected.
This still sounds problematic (though I'm not intimately familiar with the implementation details). What happens if two signers grab the XDR at the same time and then update? Won't you loose a signature?

**Comment by yuriescl** [comment]
> Not sure about adding a pending_signatures status.
> Waiting for signatures is part of the internal processing on the anchor side so it should fit within the pending_anchor status. No?

If Polaris is going to support multi-sig, it needs to have internal logic regarding the signatures since Polaris is the one creating and submitting the envelopes.
I think we do need a `pending_signatures` status, just don't expose it externally.

Idea:
1. Add `pending_signatures` to `status` field, and a new `envelope` field to the `Transaction` model.
2. Right before submitting a transaction, check if the envelope is missing signatures. If yes, set status to `pending_signatures`, store the envelope in the transaction and stop. If no, submit it to horizon.
3. The anchor would be responsible for polling transactions with status `pending_signatures` (on this case, the Anchor can expose the status, not Polaris), adding signatures to the envelope, and checking for duplicate signatures.
4. Polaris could have a new management command to check for transactions with status `pending_signatures` (similar to `poll_pending_deposits`). On this command, Polaris would check each envelope and see if no more signatures are required. If no more signatures are required, set status to `pending_anchor`, which would make Polaris go back to (2). If signatures are still required, do nothing.

**Comment by JakeUrban** [comment]
@tomerweller that was a poor example on my part, no implementation would allow direct DB updates. The idea is that the implementation is up to the anchor, who could delegate to an external signer service. 

The read-read-update-update problem you mention is common in REST API design. The 2nd update would typically return a 409 Conflict or 422 Unprocessable Entity since the 1st update was valid but also changed what must be considered a future valid update.

@yuriescl Check out my PR so far. It doesn't require another command or external status.

**Comment by JakeUrban** [comment]
The PR is ready for review FYI.
