### ISSUE TITLE
SEP24 amount parameter not being passed to form

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#292]
Steps:
- Call `/sep24/transactions/deposit/interactive` and pass `amount` as one of the form-data parameters
- Open the interactive URL
- The amount form field is not pre-filled, but it should have the value passed as `amount`

When `DepositIntegration.form_for_transaction` is called, `amount` seems to always be `None`.

**Comment by yuriescl** [comment]
Also, it seems that returning `None` from `form_for_transaction` is not supported anymore, so I suggesting updating [this snippet](https://django-polaris.readthedocs.io/en/stable/sep6_and_sep24/index.html#polaris.integrations.DepositIntegration.form_for_transaction) to this:
```
def form_for_transaction(self, transaction, post_data = None, amount = None):
    if post_data:
        return TransactionForm(transaction, post_data)
    return TransactionForm(transaction, initial={"amount": amount})
```

**Comment by JakeUrban** [comment]
@yuriescl 

I'm not sure this is a bug, but I'm testing the `amount` POST parameter to `/interactive/deposit` now. Looking at the endpoint request processing code:
```
    args_or_error = interactive_args_validation(request)
    if "error" in args_or_error:
        return args_or_error["error"]

    transaction = args_or_error["transaction"]
    asset = args_or_error["asset"]
    callback = args_or_error["callback"]
    amount = args_or_error["amount"]

    url = rdi.interactive_url(request, transaction, asset, amount, callback)
    if url:  # The anchor uses a standalone interactive flow
        return redirect(url)

    form = rdi.form_for_transaction(transaction, amount=amount)
```

`amount` is definitely passed to `form_for_transaction()`. And if we take a look at the default `DepositIntegration.form_for_transaction()` code:
```
        if transaction.amount_in:
            # we've collected transaction info
            # and don't implement KYC by default
            return

        if post_data:
            return TransactionForm(transaction, post_data)
        else:
            return TransactionForm(transaction, initial={"amount": amount})
```
We see that `amount` is used when `post_data` and `transaction.amount_in` are falsey.

**Comment by JakeUrban** [comment]
@yuriescl you're right about POST `/transactions/deposit/interactive` does not process the optional `amount` field per the SEP-24 spec. I'll update this before the 1.0 release.

However, `form_for_transaction()` can certainly return `None`, and Polaris actually depends on it to do so. This is how the developer specifies to Polaris that there are no more forms to process _or_ that Polaris should wait for the user to take some action before collecting more information.

**Comment by yuriescl** [comment]
> However, form_for_transaction() can certainly return None, and Polaris actually depends on it to do so. This is how the developer specifies to Polaris that there are no more forms to process or that Polaris should wait for the user to take some action before collecting more information.

When using this snippet:
```
    def form_for_transaction(self, transaction, post_data = None, amount = None):
        if not transaction.amount_in:
            return
        elif post_data:
            return TransactionForm(transaction, post_data)
        else:
            return TransactionForm(transaction, initial={"amount": amount})
```
I get this:

![image](https://user-images.githubusercontent.com/26092447/91069229-83e3e200-e60b-11ea-875d-f0f5b8bd3b74.png)

**Comment by JakeUrban** [comment]
Oh, the code in the docs is incorrect. That should be adjusted but thankfully there is no bug. Remove the `n.t` in the condition for `transaction.amount_in`

```
    def form_for_transaction(self, transaction, post_data = None, amount = None):
        if transaction.amount_in:
            return
```

**Comment by yuriescl** [comment]
I removed the `not` and updated Polaris to the latest commit.
Now if the form is invalid it's returning a blank form:
![image](https://user-images.githubusercontent.com/26092447/91075697-da095300-e614-11ea-88aa-cdd41f08f4ff.png)

This is being caused by `{}` being assigned to `content` here: https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep24/deposit.py#L145

Do I have to implement `DepositIntegration.content_for_template`? I thought that if the form was invalid it would just display it again.

**Comment by JakeUrban** [comment]
Ah the invalid `form` object is not being passed to the template when it is invalid. This must've happened when we transitioned to `form_for_transaction` instead of `content_for_transaction()`. I'll add that fix too.

I've realized that there are 2 migration issues and 2 bugs in Polaris currently, so I'm going to release a 13.0.2 version.

**Comment by JakeUrban** [comment]
However the fix has been pushed to master if you want to grab it from there.
