### ISSUE TITLE
Update translations before release

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#297]
Hello @oonid and @ronaldoy,

If you both could take a look at the respective translations files for `id` and `pt` prior to 1.0 that would be great. The two files you should update are listed here:
- `example/server/locale/<lang>/LC_MESSAGES/django.po`
- `polaris/polaris/locale/<lang>/LC_MESSAGES/django.po`

It looks like only minor fixes and updates are necesary.

**Comment by oonid** [comment]
hello @JakeUrban 
I have created PR #300 to update the translation for locale "id".
