### ISSUE TITLE
Implement SEP-10 2.0

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#301]
If a client thinks we are still a 1.0 anchor, they should still be able use the version they have currently installed to continue interacting with us. The old version of most SDK's `read_challenge_tx()` doesn't check the Manage Data op key.

**Comment by JakeUrban** [comment]
Clients implementing SEP-10 <2.0 use SDKs that accept an `anchorName` parameter or equivalent and ensure the Manage Data operation's key contains the value passed. This check will fail for clients reading Polaris' challenge transactions after this change.

@ronaldoy @yuriescl @morleyzhi 

Should we hold off on this upgrade? How are wallets handling different versions of SEP-10 challenges?

**Comment by ronaldoy** [comment]
I think we should ask Lobstr, Vibrant and DStoq to be sure.

**Comment by JakeUrban** [comment]
I tagged Vibrant, who should I tag for Lobstr and DStoq?

**Comment by ronaldoy** [comment]
Lobstr:  @pitsevich
DStoq: @shredding

**Comment by yuriescl** [comment]
> This check will fail for clients reading Polaris' challenge transactions after this change.

Not a blocker here, feel free to implement.

**Comment by shredding** [comment]
Sorry, I can't follow, what exactly is the change?

**Comment by JakeUrban** [comment]
@shredding I can explain, but before I do I actually take this statement back:

> Clients implementing SEP-10 <2.0 use SDKs that accept an anchorName parameter or equivalent and ensure the Manage Data operation's key contains the value passed.

The older versions of the SDK's don't check for the `anchorName` string in the Manage Data operation. So clients using an SDK version that doesn't support [SEP-10 2.0](https://github.com/stellar/stellar-protocol/pull/708) should still be able to read SEP-10 2.0 challenges with no issues. 

To answer your question now, the SDK's across the ecosystem have been releasing new versions that build and check for a SEP-10 challenge's `homeDomain` in the ManageData operation. This `homeDomain` replaced the `anchorName` field that was originally included in the operation's key.

- Clients are also expected to check that the `SIGNING_KEY` signed the challenge transaction returned
    - If an anchor doesn't have a `SIGNING_KEY`, it doesn't implement SEP-10 2.0
- Clients are also expected to check that the [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) included in the manage data operation is the same home domain as the service that requires authentication.
    - Clients can now optionally specify a `home_domain` parameter in the `POST WEB_AUTH_ENDPOINT` request body, and if the server supports issuing tokens for services on that home domain, it will include the passed value in the ManageData operation.
    - This effectively allows for SEP-10 2.0 servers to support issuing tokens for services on different FQDN's. For example, `sep24.anchor.com` and `sep31.anchor.com` could both require a SEP-10 tokens issued from `auth.anchor.com`. The anchor will use one service as the "default", and require clients to specify other valid `home_domain` values in the `POST` auth request.

Let me know if you have any questions about how this affects Lobstr. Polaris is just one anchor of many. I suspect other anchors on your wallet will begin issuing SEP-10 2.0 challenges soon.

**Comment by shredding** [comment]
Ah, okay thanks.

We don't use an SDK, we have our own implementation because that part is written in dart and there is no SDK i'm aware of.

Hence, we need to add the additional checks, but it shouldn't break as long as we don't do it.

**Comment by JakeUrban** [comment]
Right. The expectation is that all anchors and wallets eventually adopt this. The work is really on the clients to add the `SIGNING_KEY` signature check.
