### ISSUE TITLE
SEP-31 /customer: how to return a 404 response

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#303]
If `id` is passed to `/customer` and the customer does not exist, we should return a `404 Not Found` response.
[CustomerIntegration.get()](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/integrations/customers.py#L17) currently only supports raising a ValueError, which will make Polaris return a `400` response when a `404` would be more appropriate.
I didn't find any mention about a `404` response in SEP-12 spec, is this a protocol limitation or should we return `400` in all cases?

**Comment by JakeUrban** [comment]
`GET /customer` requests with an invalid `id` currently would return `400 Bad Request`. We could update this to add a 404 response, but it would only be used when `id`'s are specified. 

If they aren't, `GET /customer` would never return a 404 or 400, instead returning a 200 along with the fields required for the optional `type` passed.

**Comment by JakeUrban** [comment]
If the `id` parameter was required, I would definitely support adding a 404 response. I'm not sure how I feel about adding one in this situation. What do you think @tomerweller ?

**Comment by yuriescl** [comment]
> We could update this to add a 404 response, but it would only be used when `id`'s are specified

Yes this applies only when the `id` is passed.

**Comment by yuriescl** [comment]
I'm also not allowing other filters to be passed along with `id`, since it's a unique value.

**Comment by JakeUrban** [comment]
I think it may be the best solution to return `404`. Otherwise, clients won't be able to distinguish between ill-formed requests and non-existent users.

**Comment by JakeUrban** [comment]
This too will also require Polaris 1.0 delays
