### ISSUE TITLE
SEP-31: how to filter customer by SEP10 pubkey

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#304]
SEP-31 requires SEP-10 authentication and I assume that only a customer which belongs to the SEP-10 account can be returned in the response.
[CustomerIntegration.get()](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/integrations/customers.py#L17) currently only receives the parameters passed to the `/customer` call, which might not contain the JWT with the SEP-10 pubkey. How can I use the SEP-10 account as a filter to avoid returning a customer that is not authenticated in the request?

**Comment by JakeUrban** [comment]
This is an issue, you're right. I'll fix this bug before releasing 1.0
