### ISSUE TITLE
Add support for two-part payments

### ISSUE THREAD

**Issue by tomerweller** [stellar/django-polaris#316]
Should Polaris support two part payments and sponsored reserves?

https://www.stellar.org/developers-blog/guide-to-protocol-14-prep

**Comment by JakeUrban** [comment]
Polaris already pays for the account's creation if it doesn't exist, but it definitely should add support for two-part-payments.

**Comment by Zagan202** [comment]
## Currently the payment flow is as follows without two-part payments
1. Alice issues a payment of `SRT` to Bob
2. Bob doesn't have a trustline established with `SRT`
3. Alice's transaction fails  
4. Bob establishes a trustline for `SRT`
5. Alice retries to issue a payment of `SRT` to Bob

## The payment flow is as follows with two-part payments
1. Alice issues a payment of `SRT` to Bob
2. Bob doesn't have a trustline established with `SRT`
3. Alices's payment will instead be made as a `claimableBalance`
    - The claimant is Bob
    - The sponsor is Alice such that she can retrieve it if need be
    - **Note:** We could set predicates that state when it should be claimed by
4. Bob establishes a trustline for `SRT`
5. Bob claims the `claimableBalance` (sponsored by Alice) of `SRT`

**Comment by Zagan202** [comment]
One point of change will have to be `create_stellar_deposit`.
On line 150 there's a condition `if created or pending_trust:` 
```
        if created or pending_trust:
            # the account is pending_trust for the asset to be received
            if pending_trust and transaction.status != Transaction.STATUS.pending_trust:
                transaction.status = Transaction.STATUS.pending_trust
                transaction.save()
            return False
```
Instead of exiting here we're going to flag this transaction as a `claimableBalance` and submit it as such 
`return submit_stellar_deposit(transaction, multisig=multisig)`

**Comment by JakeUrban** [comment]
The solution steps shouldn't have the first point, because Polaris shouldn't try to make a payment before checking for the trustline.

**Comment by Zagan202** [comment]
Updating https://github.com/stellar/django-polaris/pull/341 to be compatible with the trustline flow as well as the claimable balance flow.

The claimable balance flow will occur when the key-value claimable_balance_supported: True is given via the POST req payload.

**Comment by JakeUrban** [comment]
@Zagan202 I think I know what you meant but just in case, I would start a new branch instead of building on an already-merged PR.
