### ISSUE TITLE
Add Support for Django Template Extensions

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#317]
When returning HTML from `DepositIntegration.instructions_for_pending_deposit`, I'm having to use inline CSS inside the tags, as I couldn't find an easy way to define custom CSS for Polaris templates.
Polaris has an integration function to define custom JS, it would be great to have something similar for CSS as well.

UPDATE: This issue now is about two things:
- Deprecate integrations that collect data to be used in templates
- Add support for django template extensions

The two integrations that serve the purpose template extensions can do better are:
- JS scripts() integration function
- DepositIntegration.instructions_for_pending_deposit()

`content_for_template` also returns data for templates but its content that must be sent from the backend, not computed or processed on the frontend.

**Comment by JakeUrban** [comment]
The `instructions_for_pending_deposit()` integration needs upgrading. There should be a better interface for providing instructions within the more_info template.

In the immediate future, you can use Polaris' [JS script](https://django-polaris.readthedocs.io/en/stable/sep6_and_sep24/index.html#javascript-integration) integration. Using this integration you can solve your issue a number of ways better described [here](https://dev.to/karataev/set-css-styles-with-javascript-3nl5).

**Comment by JakeUrban** [comment]
Any changes to `instructions_for_pending_deposit()` will be included in a post-v1.1 release. I'm wondering if we should replace the `text/html` content returned with a Django Template object.

The idea is the Polaris dev would load a HTML Template source file into a `Template` django object and return it. Tags can reference CSS style groupings defined from a JS script passed via the JS script integration function mentioned above.

If you don't like the idea of returning `TemplateScript` objects from the JS script integration function and would rather just replace Polaris' CSS styling altogether, see how Polaris allows developers to [override the base CSS stylesheet](https://django-polaris.readthedocs.io/en/stable/sep6_and_sep24/index.html#replacing-polaris-ui-assets) used.

**Comment by yuriescl** [comment]
> I'm wondering if we should replace the text/html content returned with a Django Template object.

Yes. Polaris could support `str` and `Template`. If it's `str`, it treats as plain text and inserts it into `more_info.html` (same as currently). If it's `Template`, it renders the template instead of `more_info.html`.
With that change, I would create a template and inherit it from `more_info.html`.
Polaris could, in the base template, add `{% block extra_head %}` and `{% block extra_body %}` to the end of `<style>` and `<body>` tags respectively, so new templates could easily add their own template-specific styles and scripts without having to override `styles.css` or adding global JS using the JS integration.

**Comment by JakeUrban** [comment]
> If it's Template, it renders the template instead of more_info.html.

The template returned wouldn't replace more_info.html, it would be inserted into it in the same way the text or HTML is inserted today.

**Comment by JakeUrban** [comment]
See how Polaris' deposit template is loaded _into_ the base template.

**Comment by yuriescl** [comment]
> > If it's Template, it renders the template instead of more_info.html.
> 
> The template returned wouldn't replace more_info.html, it would be inserted into it in the same way the text or HTML is inserted today.

I see.
But still, inserting custom CSS (include a new CSS file, for example) should not be difficult. Right now it would require either using JS or override `styles.css` entirely, correct?

**Comment by yuriescl** [comment]
Just adding the `extra_` tags would make it far easier to write new templates. This would maybe even remove the need for a JS integration since the the developer could just inherit `base.html` and just add his `<script>` tags inside `extra_body`.

**Comment by JakeUrban** [comment]
> But still, inserting custom CSS (including a new CSS file, for example) should not be difficult. Right now it would require either using JS or overriding styles.css entirely, correct?

Thats correct. You can override `base.css` entirely but you can also just make a copy and build/modify it.

**Comment by JakeUrban** [comment]
Lets clear something up about how the Template stuff will work for `instructions_for_pending_deposit()`. 

You are not going to be writing your own Template that inherits from `base.html`, you'll be writing a Template that is rendered _within_ `base.html`. 

When `instructions_for_pending_deposit()` is called, a `Template` object will be returned instead of text. This `instructions_template` will be rendered within `more_info.html` like so:
```
% block "content" %}
<section class="section receipt">
    {% if instructions_text is not none %}
    <div class="info-item">
        <div class="info-label">
            {% trans "instructions" %}
        </div>
        <div class="field-value">
            {{ instructions|safe }}
        </div>
    </div>
    {% if instructions_template is not none %}
    {% block "instructions_template" %}
    {% endblock %}
    {% endif %}
```

This `instructions_template` will contain rendered HTML code to insert into that page. See the `more_info.html` page to get a better understanding of how it works today.

The JS script integrations will likely not be removed. It is important to load JS scripts defined by the anchors within the body of the HTML doc, _not the head_. Thats why it makes more sense to provide a new integration that allows Polaris developers to put custom CSS `link` tags in the `<head>` tags, separate from the `<script>` tags loaded by the JS integration at the bottom of the body.

**Comment by yuriescl** [comment]
Understood.
I'm not sure if I agree with putting CSS/JS inside Python code (integration functions). That's why I was suggesting the `{% extra_head %}` and `{% extra_body %}` tags and so on.
There should be a better way of doing this, I'll get back to you if I have any ideas regarding that.

**Comment by JakeUrban** [comment]
Actually, we can do this today via `content_for_template()`. I could allow a `stylesheets` key that would map to a list of Polaris `TemplateLink` (think CSS TemplateScript) objects. These `TemplateLink` objects would contain the file paths to the CSS source files listed in their static directory and be rendered as `<link href=../>` tags whatever template is being rendered.

**Comment by JakeUrban** [comment]
So to review, there are two separate issues being discussed here:
- You'd like to have a better way of specifying custom CSS (as opposed to overriding base.css)
- You'd like to have better template support for deposit instructions

Hopefully both of these issues are resolves by:
- Adding this `stylesheets` key to `content_for_template()` and `TemplateLink` object, which should allow you to add CSS to the head of the HTML doc per-page displayed.
- Adding a `instructions_template` variable to the `more_info.html` template that will contain rendered HTML content passed as a `Template` object by the developer from `instructions_for_pending_deposit()`

**Comment by JakeUrban** [comment]
Looks like I didn't see [this comment ](https://github.com/stellar/django-polaris/issues/317#issuecomment-700226904) before posting the 2 comments above, does my improved solution make sense?

**Comment by yuriescl** [comment]
Here's an idea:

- Modify `base.html` by adding `extra_head` and `extra_body` tags:
```
...
        background-repeat: no-repeat;
        background-position: right 1em top 50%, 0 0;
      }
    </style>

      {% block extra_head %}
      {% endblock %}
    </head>

...

      {% endif %}
    {% endfor %}

  {% block extra_body %}
  {% endblock %}

  </body>
</html>
```

- Remove the JS integration function
- Move Polaris templates to a subfolder called `polaris` to have a structure like:
  * `templates/polaris/base.html`
  * `templates/polaris/transaction/...`
  * This avoids conflicts the Anchor templates and is a common practice for static files as well
- Update documentation suggesting that if the Anchor needs to add CSS or JS to templates, it can do it by overriding the template.  
For example, let's say the Anchor wants to add styles or scripts to `more_info.html` **only**.  
It could do it by creating a template in `templates/transaction/more_info.html`:
```
{% extends "polaris/transaction/more_info.html" %}

{% block extra_head %}
[...custom styles...]
[whatever else the Anchor wants at the end of <head>]
{% endblock %}


{% block extra_body %}
<script src='...my custom script...'></script>
[whatever else the Anchor wants at the end of <body>]
{% endblock %}
```

This allows the Anchor to override specific templates instead of loading global JS/CSS in all pages, which is the case with the current integration function.

**Comment by yuriescl** [comment]
> Looks like I didn't see [this comment ](https://github.com/stellar/django-polaris/issues/317#issuecomment-700226904) before posting the 2 comments above, does my improved solution make sense?

It does make sense but is a workaround for the already existing method, which I think is not optiomal.

**Comment by JakeUrban** [comment]
I really like your idea, but it would be a breaking change to Polaris, which something I want to avoid until 2.0. I'll create the 2.0 milestone now and begin logging breaking changes we want to make, including this one. 

If possible, I'd like to stick with our current mechanisms. However, if the other major stakeholders in Polaris want this change as well and are willing to update their implementations due to the breaking change, then we could get started on 2.0 now.

I would suggest making a post to the [Polaris Google Group](https://groups.google.com/g/stellar-polaris), which has the major Polaris stakeholders subscribed.

At the moment I don't have the bandwidth to do this change, regardless of if its 1.2 or 2.0. Depending on your needs and timeline, you're more than welcome to implement 1.2 now or 2.0 if everyone is on board.

**Comment by JakeUrban** [comment]
I hope it makes sense why I want to get major stakeholder buy-in before making a breaking change. Others need to continue updating Polaris when Protocol changes happen, including when 14 comes out. If the next version of Polaris is a breaking change, it's more work the developer must do immediately.

**Comment by JakeUrban** [comment]
https://github.com/stellar/django-polaris/issues/318

**Comment by yuriescl** [comment]
We could add the advanced template support in 1.2 and keep the JS integration as it is.
In 2.0 we could deprecate the integration function and remove it later in 2.x.

**Comment by yuriescl** [comment]
I'll open a discussion in the Google Group.

**Comment by yuriescl** [comment]
However I do think moving the templates to a `polaris` subfolder is a must and should be done soon. It's not a breaking change since Anchors are not likely to be overriding templates at the moment.

**Comment by JakeUrban** [comment]
Thanks! I actually like that idea of deprecation. As long as the 2.0 changes can be made in a way that isn't disruptive to the current system I would be alright with that. If conversation picks up in the google group we can continue there, otherwise lets go to the [new issue](https://github.com/stellar/django-polaris/issues/318) for this problem.

That way, we can continue discussing the deposit instructions fix here. Can I change the title of this issue?

**Comment by yuriescl** [comment]
I agree, yes.

**Comment by JakeUrban** [comment]
> However I do think moving the templates to a polaris subfolder would be a priority. It's not a breaking change since Anchors are not likely to be overriding templates at the moment.

We already have the following `templates` directory structure:
![Screen Shot 2020-09-28 at 1 19 11 PM](https://user-images.githubusercontent.com/10968980/94481847-3f5ce080-018d-11eb-86a9-6e15dc6b3700.png)

But I see you mean you'd like to see something like so:

templates/
- polaris/
    - deposit/
        - form.html
    - django/
        - ...
    - transaction/
        - more_info.html
    - widgets/
        - ...
    - withdraw/
        - form.html
    - base.html
    - error.html

**Comment by yuriescl** [comment]
Yes

**Comment by JakeUrban** [comment]
I think we can do that in 1.2 and just let the strategic anchors know via the group.

**Comment by JakeUrban** [comment]
I think I'm going to use the solution you outlined for `extra_head`/`extra_body` but for the instructions.

Developers will define an `instructions` block, instead of returning something from a `instructions_for_pending_deposits()` function. I think I'll be adding the `extra_head`/`extra_body` blocks too.

The docs will have to be updated to list what variables are passed to each template.

**Comment by yuriescl** [comment]
I agree, HTML/CSS/JS should not be inside `.py` files.

**Comment by JakeUrban** [comment]
The Django 2.2 docs don't have [this docs section](https://docs.djangoproject.com/en/3.1/howto/overriding-templates/#extending-an-overridden-template) but it looks like template extensions work still, so thats good.

I'm guessing 2.2 has the same functionality but didn't have the docs section.

**Comment by yuriescl** [comment]
I've tested on 2.2 and it works.
