### ISSUE TITLE
Ensure docker-compose build works after copying env file

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#320]
Lawrence had an issue where his `collectstatic` directory was empty locally (since he hadn't built it yet), and so when the container generated the files within the container, they were quickly overwritten because the local directory didn't have them

Strangely, when we ran `collectstatic` in the docker container post-launch, the files were generated and copied to the localhost.

Understand how this works and how we can ensure the docker setup doesn't require any local setup other than an environment file.

@Zagan202

**Comment by yuriescl** [comment]
Is there a way to reproduce this?

**Comment by JakeUrban** [comment]
I just tried myself and couldn't reproduce, although I do get this in the javascript console:
<img width="954" alt="Screen Shot 2020-10-01 at 2 03 09 PM" src="https://user-images.githubusercontent.com/10968980/94863394-3f5c1b00-03ef-11eb-8571-a04418dc7251.png">

**Comment by JakeUrban** [comment]
Leaving open but taking it off our to-do list
