### ISSUE TITLE
Feature Request: custom response status codes from integration functions

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#321]
I'd like to be able to return custom status codes from integration functions like `process_sep6_deposit()`.
Polaris [currently has](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep6/deposit.py#L53):
```
try:
    integration_response = rwi.process_sep6_request(args, transaction)
except ValueError as e:
    return render_error_response(str(e))
try:
    response, status_code = validate_response(
        args, integration_response, transaction
    )
except ValueError:
    return render_error_response(
        _("unable to process the request"), status_code=500
    )


```

It could have something like:
```
# polaris/sep6/deposit.py

from rest_framework.exceptions import APIException

...

try:
    integration_response = rwi.process_sep6_request(args, transaction)
except ValueError as e:
    return render_error_response(str(e))
except APIException as e:
    # It would be great to be able to return a dict+status code from the integration function,
    #  rest_framework might have built-in support for that
    return render_error_response(str(e), status_code=e.status_code)

try:
    response, status_code = validate_response(
        args, integration_response, transaction
    )
except ValueError:
    return render_error_response(
        _("unable to process the request"), status_code=500
    )
```

**Comment by yuriescl** [comment]
This seems to be extra protocol since the SEPs don't mention support for other status codes.
But I'd like to return statuses like `503` for a specific scenario.
Raising an exception sounds better than returning a tuple.

**Comment by yuriescl** [comment]
Reference: https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L86

**Comment by JakeUrban** [comment]
Part of Polaris' value is enforcing the SEP standards, and I'm not convinced allowing anchors to return non-standard status codes is a good idea.

**Comment by yuriescl** [comment]
Both [SEP-6](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#6-error) and [SEP-24](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#6-error) allow other status codes:
_Every other HTTP status code will be considered an error. The body should contain a string indicating the error details. This error is in a human readable format in the language indicated in the request and is intended to be displayed by the wallet._

Polaris currently returns error 500 for internal errors, but error 500 is generic and the error message can't be directly set by the Anchor unless it raises something like a `ValueError`, which is not ideal for a "server busy" response for example.

**Comment by JakeUrban** [comment]
Ok, I can see why this would be valuable.

I like your example here:
```
try:
    integration_response = rwi.process_sep6_request(args, transaction)
except ValueError as e:
    return render_error_response(str(e))
except APIException as e:
    # It would be great to be able to return a dict+status code from the integration function,
    #  rest_framework might have built-in support for that
    return render_error_response(str(e), status_code=e.status_code)
```

While it might be better to do somethinig like this:
```
try:
    integration_response, status_code = rwi.process_sep6_request(args, transaction)
```

But this would be a breaking change. If you'd like, we could make that change in 2.0 along with the other breaking changes we're waiting on. Is `APIException` from `rest_framework`? If so, then we can use that. Otherwise Polaris might have to define it's own exception objects, which frankly it probably should do in 2.0.

**Comment by JakeUrban** [comment]
I accidentally push the code to master without a PR. But here is the [commit](https://github.com/stellar/django-polaris/commit/5441deccc15dd3c90e3179b958276217bc0b08d4)

**Comment by yuriescl** [comment]
@JakeUrban Thanks for the patch! It's a simple but very useful change.

About this idea:
```
try:
    integration_response, status_code = rwi.process_sep6_request(args, transaction)
```
It is simpler but Polaris is already based on exception handling for integration functions, I don't think it's worth changing that.
