### ISSUE TITLE
check_trustlines: tx failed with codes

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#339]
I had a deposit with status `pending_trust`, then added the trust and ran `check_trustlines`:
```
$ python manage.py check_trustlines
polaris.apps: SECURE_SSL_REDIRECT is required to redirect HTTP traffic to HTTPS 
polaris.apps: SECURE_PROXY_SSL_HEADER should only be set if Polaris is running b
ehind an HTTPS reverse proxy.                                                   
polaris.utils: tx failed with codes: [OperationResult(code=opINNER, tr=<stellar_
sdk.xdr.StellarXDR_pack.nullclass object at 0x7f9ddbfffd60>)]. Result XDR: AAAAA
AAAAGT/////AAAAAQAAAAAAAAAB/////wAAAAA=
```

Any ideas of what might have happened?

**Comment by JakeUrban** [comment]
![Screen Shot 2020-10-14 at 10 13 11 AM](https://user-images.githubusercontent.com/10968980/96022563-e5535080-0e05-11eb-86ff-874349ca82b4.png)

**Comment by JakeUrban** [comment]
![Uploading Screen Shot 2020-10-14 at 10.15.32 AM.png…]()

**Comment by JakeUrban** [comment]
![Screen Shot 2020-10-14 at 10 15 32 AM](https://user-images.githubusercontent.com/10968980/96022799-45e28d80-0e06-11eb-9e23-066134d1044a.png)

**Comment by JakeUrban** [comment]
Your `amount` is 0?

**Comment by yuriescl** [comment]
Based on the outputs I pasted above, `amount_in == 0.0005`, I'm not sure why it's 0 in the envelope.

**Comment by JakeUrban** [comment]
What are the asset's significant decimals?

**Comment by yuriescl** [comment]
`significant_decimals == 2`
Got the problem, thanks!
