### ISSUE TITLE
Template Extensions do not work

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#344]
```
>>> TemplateHTMLRenderer().resolve_template(["polaris/base.html"]).origin.name
'/code/server/templates/polaris/base.html'
>>> TemplateHTMLRenderer().resolve_template(["polaris/deposit.html"]).origin.name
'/code/polaris/polaris/templates/polaris/deposit.html'
```

And `/code/polaris/polaris/templates/polaris/deposit.html` has a top line:
`{% extends "./base.html" %} {% load i18n %}`

So whenever we use the deposit template, it uses Polaris' `base.html` instead of the one found by django's configured template engine. Essentially, we're hard coding the template when it shouldn't be hard-coded.

This means Polaris developers cannot actually override Polaris' `deposit.html`, `withdraw.html`, or `more_info.html` templates. They can only extend Polaris' `base.html` file.

I'll need to release a patch version.

**Comment by yuriescl** [comment]
I'm using Polaris 1.1.3 and the extensions are working for me.
I have a `app/templates/polaris/more_info.html` which extends `polaris/more_info.html`:
```
{% extends "polaris/more_info.html" %}
{% load i18n %}

{% block 'title' %}
<title>{% trans "Transaction More Info" %}</title>
{% endblock %}

{% block "instructions" %}
  {% if transaction.kind == "deposit" %}
    {% if transaction.asset.code == "..." %}
    ...
{% endblock "instructions" %}
```

To test the issue you mentioned, I created a blank `app/templates/polaris/base.html` and it rendered a blank page, as expected.
So I couldn't reproduce this issue, or maybe I didn't understand it.

**Comment by yuriescl** [comment]
> To test the issue you mentioned, I created a blank app/templates/polaris/base.html and it rendered a blank page, as expected.

Another test I did was, on my `app/templates/polaris/base.html`:
```
{% extends "polaris/base.html" %}

{% block 'extra_body' %}
<script>
test
</script>
{% endblock %}
```

That properly rendered `polaris/deposit.html` (which I didn't override it on my app) and `app/templates/polaris/more_info.html` both containing my `extra_body` content.
So it seems to be all working:
`app/templates/polaris/more_info.html` ←`polaris/more_info.html` ← `app/templates/polaris/base.html` ←`polaris/base.html`

**Comment by JakeUrban** [comment]
Ok, thanks for letting me know. I'm looking at the [1.1.3 source code](https://github.com/JakeUrban/django-polaris/blob/1.1.3/polaris/polaris/templates/polaris/deposit.html) and it seems to have the same `{ extends "./base.html" }` code, which is what I thought was the problem in [master](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/templates/polaris/deposit.html).

Something is wrong with the testanchor.stellar.org deployment, our reference server template extensions are not being selected over the default Polaris templates, so I cannot skip the email confirmation step. I've been testing this with the deposit flow.

**Comment by JakeUrban** [comment]
You're not going to believe this, but the `{ block extra_body }` declaration needs to match the exact syntax used in the base template. 

The base `polaris/template/polaris/base.html`:
```
    {# Rendered via custom extra_body template #}
    {% block 'extra_body' %}
    {% endblock %}
```

My `server/template/polaris/base.html`:
```
{% block extra_body %}
...
{% endblock %}
```

I changed it to:
```
{% block "extra_body" %}
...
{% endblock %}
```
No luck.

I tried it with this:

```
{% block 'extra_body' %}
...
{% endblock %}
```

Boom, works.

**Comment by yuriescl** [comment]
@JakeUrban This is related https://github.com/stellar/django-polaris/pull/342
