### ISSUE TITLE
Remove check trustlines functionality - support only claimable balances

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#346]
@Zagan202 originally made a PR with this change but it makes sense to support both CBs and checking trust-lines until 2.0 release.

**Comment by antb123** [comment]
I would suggest that it makes sense to wait for wallet support .
At least the wallet viewer, https://accountviewer.stellar.org/ and/or stellarterm, 

Thanks

**Comment by JakeUrban** [comment]
Definitely, we wouldn’t make this change until it was adapted in most major wallets. Considering the UX improvement we would hope that’s sooner rather than later.

**Comment by JakeUrban** [comment]
I'm going to remove the milestone target on this issue since we'll only want to implement this when we're 100% confident its no longer needed in the ecosystem.

**Comment by JakeUrban** [comment]
Closing this issue because claimable balance adoption has been slower than expected and it is likely Polaris will always need to offer this functionality.
