### ISSUE TITLE
UI amount scientific notation

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#347]
More info page should not display scientific notation for amount, since it might be confusing for the user to read:

![2020-11-05_17-39](https://user-images.githubusercontent.com/26092447/98293898-d176b680-1f8d-11eb-97ab-57e13e033f68.png)

Suggestion:

![2020-11-05_17-40](https://user-images.githubusercontent.com/26092447/98293999-f9feb080-1f8d-11eb-8636-581e8d9e674d.png)

**Comment by JakeUrban** [comment]
This is something Django does when rendering small float values, and unfortunately Django doesn't provide a ton of flexibility here. I'll have to check if this is possible, otherwise we might have to develop a work around. This is currently a low-priority task.
