### ISSUE TITLE
Feature Request: SEP-2 Federation

### ISSUE THREAD

**Issue by antb123** [stellar/django-polaris#357]
### What problem does your feature solve?
allow easier support for crypto withdrawals

### What would you like to see?

Support for federation forward type for crypto

https://www.stellar.org/developers/guides/concepts/federation.html

both apay and naobtc support this type of request - (and flutterwave used to support something similar)

For withdrawals
fed = 'https://www.naobtc.com/api/federation?type=name&q=' + quote_plus(benef_ac) + "*naobtc.com"
fed = 'https://api.apay.io/api/federation?type=name&q=' + quote_plus(benef_ac) + "*apay.io"

this would add the transaction to the transactions table and process the same as a withdraw.

This could be extended at a later date to support federation type=forward in the future if needed.
example:
```
import requests
add ='1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2'
fed = 'https://api.apay.io/api/federation?type=name&q=' + add + "*apay.io"
f = requests.get(fed)
print(f.text)
{"stellar_address":"1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2*apay.io","memo":"0BNxNZYqeAui/zznWSvMrnrbFT+7","account_id":"GCR3L4I5C2WE4C5BNHEFHLFSIYHGLZRDAUG3MOWL7R3CVVSI4XL47OTJ","memo_type":"text"}
```
### What alternatives are there?

Have users use sep6/24

**Comment by JakeUrban** [comment]
Thanks for the issue Anthony, I agree Polaris should support Federation/Reverse Federation. I'll target the 1.2 release for this feature unless @yuriescl wants the features added in recent PRs released prior to this.

**Comment by yuriescl** [comment]
> Thanks for the issue Anthony, I agree Polaris should support Federation/Reverse Federation. I'll target the 1.2 release for this feature unless @yuriescl wants the features added in recent PRs released prior to this.

`1.2` is good for me, ty

**Comment by JakeUrban** [comment]
I moved this to 1.3 because we're going to release a 1.2 as soon as claimable balances are ready, which will happen well before SEP-2 is supported.

**Comment by JakeUrban** [comment]
I've decided not to implement SEP-2 Federation in Polaris. The reason is that Polaris would not be able to validate the request parameters (`q`  values, specifically where `type=name` cannot be validated ) and it does not track user data. This means Polaris support would simply be a wrapper and all logic would be implemented by the anchor. 

If developers want their anchor to support SEP-2 federation, they can still do so by adding an endpoint to their django app and adding the federation URL to their TOML.
