### ISSUE TITLE
Docs: Create SEP-6 tutorials

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#364]
The only tutorial in our docs is for SEP-24. There should be tutorials for all transfer SEPs.

**Comment by antb123** [comment]
We have written up something with examples in python. Maybe we can clean it up and merge it in?

**Comment by JakeUrban** [comment]
We have a SEP-24 tutorial already but you’re welcome to submit a PR for a SEP-6 tutorial! It would need to match the format/style of our current docs (.rst markdown).

**Comment by JakeUrban** [comment]
closing because we have a ticket for refactoring the entire docs: #555
