### ISSUE TITLE
Allow developers to specify a MAX_TRANSACTION_FEE_STROOPS variable for allowing higher fees

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#366]
Polaris currently submits transactions with the base fee as reported by the [Python SDK](https://github.com/StellarCN/py-stellar-base/blob/275d9cb7c679801b4452597c0bc3994a2779096f/stellar_sdk/server.py#L530).

**Comment by tomerweller** [comment]
This seems like an unnecessary level of indirectness. Why not just have the anchor specify the max fee they're willing to pay?

**Comment by JakeUrban** [comment]
A fee is calculated as `base_fee * # of ops`. The python SDK [asks for the base_fee](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_sdk/transaction_builder.py#L56) when constructing transactions, and ultimately does the final fee calculation when calling [build()](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_sdk/transaction_builder.py#L78).

Apart from the Python SDK, a limit can be dangerous to set. Imagine traffic increases significantly and fees are increased due to surge pricing. A limit would effectively halt the anchor's service. I'm assuming anchors would rather use a multiplier to ensure their transactions are submitted than stop the service if it goes too high.
