### ISSUE TITLE
Update translation files for v1.2

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#373]
@ronaldoy @oonid could you update the following files for your respective languages?

- `polaris/polaris/locale/id/LC_MESSAGES/django.po`
- `polaris/polaris/locale/pt/LC_MESSAGES/django.po`
- `example/server/locale/id/LC_MESSAGES/django.po`
- `example/server/locale/pt/LC_MESSAGES/django.po`

I've refreshed the files so there are some missing translations. Thank you both!

**Comment by ronaldoy** [comment]
Sure!

**Comment by oonid** [comment]
I have translated the locale id in #375
