### ISSUE TITLE
SEP24 amount symbol overflow

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#406]
Currently, if `asset.symbol` has many characters, the symbol overflows the amount input field:

![image](https://user-images.githubusercontent.com/26092447/113581861-1450bf00-95fe-11eb-84b3-f1517f219552.png)

A workaround is to dynamically set the input padding via JS:
```
const icon = document.querySelector('#id_amount').previousElementSibling;
const iconWidthStr = getComputedStyle(icon).width;
const iconWidthFloat = parseFloat(iconWidthStr.replace(/px/,""));
const iconPaddingLeftStr = getComputedStyle(icon).paddingLeft;
const iconPaddingLeftFloat = parseFloat(iconPaddingLeftStr.replace(/px/,""));
const amountElem = document.getElementById('id_amount');
amountElem.style.paddingLeft = (iconWidthFloat + iconPaddingLeftFloat) + 'px';
```

Anchors might wanna display the asset code instead of the symbol to make it more clear to the user what's the currency being deposited/withdrawn, but it would require a workaround to prevent that overflow.
Polaris could support many characters in the symbol by default.

**Comment by JakeUrban** [comment]
Thanks for the idea, I think this is the right approach.
