### ISSUE TITLE
SEP24 amount fast typing

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#407]
In SEP24 amount field, if the user types `0.01` too fast, the `Total` value becomes `0`:

![image](https://user-images.githubusercontent.com/26092447/113583258-ce94f600-95ff-11eb-9b20-9a32b039a29b.png)

If he types slowly the total is calculated as expected:

![image](https://user-images.githubusercontent.com/26092447/113583294-dbb1e500-95ff-11eb-8db1-94858e98cba9.png)

**Comment by yuriescl** [comment]
This is probably a duplicate of #402

**Comment by JakeUrban** [comment]
It is a duplicate but thanks for reporting, this will be fixed in the next minor version release.
