### ISSUE TITLE
How to get request instance

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#412]
I need to get some header information from the HTTP request when inside `process_sep6_request` and `form_for_transaction`, but I couldn't find a way to do that and would like some insights on possible solutions.
Thanks.

**Comment by JakeUrban** [comment]
Hi @yuriescl , unfortunately there isn't a straightforward way to do that right now. One way to do it would be to add a middleware component that saves the header information you're looking for in the DB or some cache, and retrieve ​it from the integration functions.

What header information are you looking for? It may make sense to add the `request` object from Django to each integration function thats called within a request/response cycle.

**Comment by yuriescl** [comment]
I was looking for a way to get the user IP address. I thought about writing a middleware but I'm not sure how I'd associate each request to its respective integration function.

**Comment by JakeUrban** [comment]
You don't have to associate it with a function. You can add a middleware that adds the header info for each request and removes it on each response. See https://docs.djangoproject.com/en/2.2/topics/cache/#accessing-the-cache

**Comment by yuriescl** [comment]
> You don't have to associate it with a function. You can add a middleware that adds the header info for each request and removes it on each response. See https://docs.djangoproject.com/en/2.2/topics/cache/#accessing-the-cache

This can work, but maybe it's better to just pass the request object. I'm closing this and will comment in the other issue. Thanks.
