### ISSUE TITLE
SEP-24: memo_type is being set to hash by default

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#428]
Polaris is setting memo_type as hash by default, this is an issue if the Wallet wants to pass an empty value for both fields, since they're optional in the specification.
https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep24/deposit.py#L401

**Comment by yuriescl** [comment]
SEP-6 is setting memo_type as text by default:
https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep6/deposit.py#L56

SEP-31 might have this issue as well

**Comment by JakeUrban** [comment]
I'm not sure this is a bug. An empty string is not one of the accepted values for the `memo_type` parameter (which accepts "hash", "text", and "id". Why pass the `memo`/`memo_type` parameters at all if they're empty?

**Comment by yuriescl** [comment]
> I'm not sure this is a bug. An empty string is not one of the accepted values for the `memo_type` parameter (which accepts "hash", "text", and "id". Why pass the `memo`/`memo_type` parameters at all if they're empty?

Sorry, I meant not pass them. Polaris will default the memo_type to hash but leave memo empty. This is unlikely going to cause problems since wallets won't pass an empty memo with memo_type hash. But storing `memo_type` as `hash` for an empty memo seem a bit inconsistent.
I'm closing this as it's not a bug, you're right.
