### ISSUE TITLE
Add setting to make fees additive

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#452]
Polaris is currently deducting the fees from `amount_in`:
`amount_out = amount_in - amount_fee`

Do you have any suggestions on how to make the fees additive, in a way that, for example, in a deposit, the user will send `amount_in + amount_fee` in order to receive `amount_out` on his Account.
Same for withdrawal, the user would send a Stellar transaction with the fees included, then he would receive the desired amount on his destination address.

At the moment the user enters the amount but he receives less. I want him to enter the amount he wants to receive.

**Comment by yuriescl** [comment]
I'm asking because it seems a bit of work, like refactoring the SEP-24 forms, etc. Just looking for some guidance.

**Comment by JakeUrban** [comment]
Hi @yuriescl, I've done this for another deployment of Polaris and it only requires adding the calculated fee amount to `Transaction.amount_in` in `after_form_validation()`. Does that work for you?

**Comment by yuriescl** [comment]
But what about `TransactionForm`, how can I make it behave in a way that the user enters the amount he wants to receive, and sees how much he'll have to pay (instead of the opposite)? I imagined I'd have to override the JavaScript logic, etc.

**Comment by JakeUrban** [comment]
Ah you're right, I replaced the base template and did use the fee table for that deployment. You would have to replace the base template and adjust the javascript.

This is probably worth adding a setting for though. Can I change the title of this issue to "Add setting to make fees additive"?

**Comment by yuriescl** [comment]
Yes, that would be much appreciated, thanks!
