### ISSUE TITLE
SECURE_PROXY_SSL_HEADER warning

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#453]
Polaris is giving this warning:
```
SECURE_PROXY_SSL_HEADER should only be set if Polaris is running behind an HTTPS reverse proxy.
```
Although the information is correct, it's spamming the logs. Maybe it should be a debug log instead of a warning log.

**Comment by JakeUrban** [comment]
I agree, adding this setting doesn't make the service vulnerable in any way so it shouldn't be a warning.

**Comment by JakeUrban** [comment]
I'm going to include this in 1.5, along with making fees additive (#452)
