### ISSUE TITLE
more_info_url missing parameters in /transactions

### ISSUE THREAD

**Issue by ronaldoy** [stellar/django-polaris#47]
When the transaction list is requested, more_info_url comes without parameters. 
<img width="929" alt="Screen Shot 2019-12-12 at 10 15 20 AM" src="https://user-images.githubusercontent.com/1394400/70715412-02406400-1cc9-11ea-9b54-68082bfd4848.png">
<img width="719" alt="Screen Shot 2019-12-12 at 10 20 53 AM" src="https://user-images.githubusercontent.com/1394400/70715467-1c7a4200-1cc9-11ea-9fc7-543e0356af10.png">

**Comment by JakeUrban** [comment]
@ronaldoy thanks for pointing this out. I see the issue in the source code and will make sure the next release fixes this.
