### ISSUE TITLE
Implement SEP-38: Anchor RFQ API

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#476]
Add support for SEP-38 and integrate the functionality into SEP-6 and SEP-31 as defined by the protocols:
- [SEP-38 specification](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md)
- [SEP-31 support for SEP-38](https://github.com/stellar/stellar-protocol/pull/932)
- [SEP-6 support for SEP-38](https://github.com/stellar/stellar-protocol/pull/973)

## Discussion of Changes

The changes below attempt to be exhaustive but are likely not.

### Data Model

There are three approaches we could take:
- Implement as much as possible
- Leave all modeling to the anchor
- Something in between

Implementing as much as possible allows Polaris to handle as much of the quote-related functionality as possible, which minimizes the code the anchor needs to write to have a functioning SEP-38 integration, but forces the anchor to use an existing data model that may be incomplete for their use case. Leaving all modeling to the anchor maximizes the amount of flexibility when designing their own model, but requires them to write more code.

Attempting to add a self-sufficient data model in Polaris would involve not only adding a `Quote` model, but also `OffChainAsset`, `SellDeliveryMethod`, and `BuyDeliveryMethod` models. This would allow us to implement the `GET /info` without an integration function. However, I don't believe this is worth it since all endpoints other than `GET /quote` will require integration functions to source exchange prices.

We can strike a balance and only provide a single `Quote` model:

- `Quote` model
     - `id` - uuid
     - `type` - string (`firm`, or `indicative`)
     - `buy_asset` - string ([Asset Identification Format](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#asset-identification-format))
     - `sell_asset` - string ([Asset Identification Format](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#asset-identification-format))
     - `price` - nullable(decimal)
     - `sell_amount` - nullable(decimal)
     - `buy_amount` - nullable(decimal)
         - The 3 columns above must be nullable because exchange price for indicative quotes is determined at time of delivery
     - `expires_at` - nullable(UTC datetime)
         - null for indicative quotes

This model will allow us to respond to `GET /quote` requests without an integration function, but the remaining endpoints will require one. Anchors will be expected to create the data model needed for all off-chain asset information.

Changes to existing models:

- `Transaction` model
    - Add `quote` - nullable(foreign key column)
    - Update `kind` - add `deposit-exchange` and `withdrawal-exchange` values

#### SEP-38

All SEP-38 related integration functions will be contained within a `SEP38AnchorIntegration` 

We'll need the following integrations, named after their endpoints:
- `.info()`
- `.prices()`
- `.price()`
- `.quote()`

All integrations will need to be passed the validated request body. `.info()` and `.prices()` will likely need to return the complete response bodies that Polaris will validate before returning to the client. `.price()` will likely only need to return a `Decimal` object and `quote` will likely return a `Quote` model object.

Obviously, we'll need to add all SEp-38 endpoints to the server's url configuration as well.

#### SEP-6

SEP-6 will need to add the following endpoints:
- `GET /deposit-exchange`
- `GET /withdraw-exchange`

I think the pair of these integrations warrant a new integration on the `DepositIntegration` and `WithdrawalIntegration`, `process_sep6_exchange_request()`. It should behave similarly to the original `process_sep6_request()` function.

The functions that validate the response bodies of the `GET /info` endpoint will also need to be adjusted.

The `GET /fee` endpoint will need to be updated to accept the new `kind` parameter values.

The `TransactionSerializer` will need to be updated to return the optional `GET /transaction(s)` response attributes added for transaction using quotes.

#### SEP-31

SEP-31 doesn't have any new endpoints, so it's existing integration functions should work.

The functions that validate the response body of the `GET /info` endpoint will need to be adjusted.

The `SEP31TransactionSerializer` will need to be updated to return the optional `GET /transaction/:id` response attributes added for transaction using quotes.

#### Rails Integrations

CLI-command code that calls the rails integration functions will need to be adjusted to ensure transactions that use indicative quotes have the `Quote.price`, `Quote.buy_amount`, and `Quote.sell_amount` attributes saved after initiating delivery of funds to a user.

Rails integrations & CLI commands will also need to check if the funds were delivered prior to a quote's expiration and handle the case where the quote has expired properly. More thought needs to go into what that entails.

**Comment by lijamie98** [comment]
The fields of `Quote` seem general enough. But we may also make it extensible for extra information, such as FX source, etc. If we add a `memo` field for data and `memo_type` for how to parse the memo, this will allow the anchor to add extensible information without having to re-write the `Quote` model.

Another possibility is to have everything available in Polaris. The anchor can choose what to activate if they find Polaris complete. If they think Polaris isn't complete, they can choose: 

1. Replace the function.
2. Extend the function.

**Comment by lijamie98** [comment]
Do we need to create a quote record if the type is `indicative`?
