### ISSUE TITLE
SEP-24 fee is NaN in version 1.5

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#478]
I'm getting `NaN` fees after upgrading to v1.5:

![2021-08-16_16-02](https://user-images.githubusercontent.com/26092447/129616114-94c9c13e-3935-458d-93ee-3c5d3821b6c2.png)

When starting to debug the JS I think I found the issue:

![2021-08-16_16-19](https://user-images.githubusercontent.com/26092447/129617984-7a1575e8-c31d-4a01-a460-5c40eb20344a.png)

**Comment by JakeUrban** [comment]
Thanks for pointing this out, I'll start on a fix asap.

**Comment by JakeUrban** [comment]
What are your fee stats? Just so I have the full picture.

**Comment by yuriescl** [comment]
I'm not sure if you mean what are the values for the fees. I was doing a deposit, so:
`deposit_fee_fixed = 0`
`deposit_fee_percent = 1`
