### ISSUE TITLE
SEP-24 allow user to enter amount_out instead of amount_in

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#480]
When using additive fees (introduced in Polaris `v1.5`), the amount entered by the user becomes `amount_in`:

![2021-08-16_23-24](https://user-images.githubusercontent.com/26092447/129654065-a557896e-1454-410d-9d5e-09d83ffdc075.png)

![2021-08-16_23-25](https://user-images.githubusercontent.com/26092447/129654088-78ec0d71-76fa-4e3a-8df0-dddec723dd47.png)

Is there an easy way to make the user enter `amount_out` instead? The Anchor would add the fees and generate an `amount_in`.
This scenario is relevant when the user wants to deposit/withdrawal an exact amount, without having to worry about fee calculation (specially relevant for crypto currencies with invoice systems, which have an amount and maybe the user just wants to pay that invoice).

**Comment by JakeUrban** [comment]
Hi @yuriescl, the pictures above indicate that `ADDITIVE_FEES_ENABLED` is `False`. If it was `True`, and you entered 99, the fee would be 1 and the Total would be 100.

**Comment by yuriescl** [comment]
You're right, I set it to `True` but maybe forgot to reload the server, sorry.
I wonder if the labels are easy to understand, though.
Maybe we could change the labels in the TransactionForm similarly to the more info page. Just an idea, though. I'm closing this as it's not an issue, thanks!
