### ISSUE TITLE
SEP-24 fees are 0 when page is refreshed

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#484]
In SEP-24, when I put an amount, the fee is updated correctly. but when I refresh the page (F5) the amount is still there but the fee is initially 0. Editing the amount updates the fees.

**Comment by JakeUrban** [comment]
Interesting. I'll take a look, thanks for filing.

**Comment by JakeUrban** [comment]
Removing the milestone because this bug fix would be included in a patch release.
