### ISSUE TITLE
SEP10 doesn't support urlencoded content type

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#50]
If you try to post to the SEP-10 challenge endpoint using `application/x-www-form-urlencoded`, we try to split the body on the '<' character, but there shouldn't be a '<' character in the body.  I think this is a misunderstanding of the sep-10 docs where it says `Content-Type: application/x-www-form-urlencoded, body: transaction=<signed XDR (URL-encoded)>)` I don' think we actually expect angled brackets there, thats just a signifier that its a token.  We should be able to just split the following line on `=` instead.

https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep10auth/views.py#L49

**Comment by ire-and-curses** [comment]
Maybe the SEP contents can be made clearer? E.g. Slack API [doc](https://api.slack.com/reference/surfaces/formatting) does it in a way that allows no ambiguity:

> To mention a user group in app-published text, you need to provide the group ID in the following general syntax:
> 
> `<!subteam^ID>`
> 
> !subteam^ is a literal string that should not change, but ID should be replaced with the actual user group ID. Here's an example:
> 
> Hey <!subteam^SAZ94GDB8>, there's a new task in your queue.
