### ISSUE TITLE
Missing static scripts

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#513]
Seems like `static/polaris/scripts` is missing from the repository? It's being used by `base.html` though:
![test](https://user-images.githubusercontent.com/26092447/131923975-6ec5a665-bdc0-40ae-bc27-3f44bfeded54.png)

**Comment by yuriescl** [comment]
Seems like it's just missing when installed via pip. It's in the source code but not in `python3.9/site-packages/polaris`

**Comment by yuriescl** [comment]
How to reproduce:
- Create a new clean virtual environment
- Activate virtual environment
- pip install django-polaris==2.0.0
- go to virtualenv directory and look for `site-packages/polaris`
- `scripts` dir is missing from `static/polaris`

**Comment by JakeUrban** [comment]
Ah, I need to add the `scripts` directory to the `MANIFEST.in` file which is what specifies which static files to include in the packaged source code.
