### ISSUE TITLE
SEP-24 Allow template name override

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#517]
SEP-24 currently uses hardcoded template names.
For example, in [endpoints.py](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/shared/endpoints.py#L77):
```
return Response(context, template_name="polaris/more_info.html")
```

The only way to override the template is by extending it in `app/templates/polaris/more_info.html`. But in order to have different templates for each asset/deposit/rail, the Anchor needs to use multiple `{% include %}` inside the same `more_info.html`:
```
{% if kind == "deposit" and rail == "somerail" %}
    {% include "app/templates/deposit_custom_template.html %}
{% else %}
    {% include "app/templates/some_other_template.html %}
```

There are a few issues with this:
- Makes it difficult to read/maintain the same template by adding so many conditions.
- Makes it difficult to add custom css/js in `{% block %}` overrides from the included template

It would be simpler to be able to specify the template to render.
I suggest support returning a tuple from `content_for_template`. So if the Anchor returns a tuple, the first element can be the template name (`str`) and the second can be the content (`dict`):
```
def content_for_template(
        self,
        request: Request,
        template: Template,
        form: Optional[forms.Form] = None,
        transaction: Optional[Transaction] = None,
        *args: List,
        **kwargs: Dict
    ) -> Union[Tuple[str, Optional[Dict]], Optional[Dict]]:
    return "app/templates/custom_template.html", {
        "transaction": transaction,
        "param1": param1
    }
```

**Comment by yuriescl** [comment]
This is the kind of code I'd like to avoid in `app/templates/polaris/more_info.html`:
```
{% block "instructions" %}
  {% if rail == "rail1" %}
    {% if transaction.kind == "deposit" %}
      {% include "app/rail1/deposit/more_info.html" %}
    {% elif transaction.kind == "withdrawal" %}
      {% include "app/rail1/withdrawal/more_info.html" %}
    {% endif %}
  {% endif %}
{% endblock %}
```

**Comment by JakeUrban** [comment]
I agree, it makes more sense to allow the anchor to specify which template is rendered instead of hard-coding it. Is your current solution becoming un-maintainable or can we postpone this change to 3.0 since it's breaking?

**Comment by yuriescl** [comment]
This can be postponed to 3.0

**Comment by JakeUrban** [comment]
Hey @yuriescl, I actually added this functionality in 2.1. Instead of returning a tuple from `content_for_template()`, Polaris looks for a `template_name` key-value pair in the dictionary returned.
