### ISSUE TITLE
make_memo return value is not used

### ISSUE THREAD

**Issue by lijamie98** [stellar/django-polaris#538]
https://github.com/stellar/django-polaris/blob/4d0ea8ea2a3952a7895d4363c62ddabe0afa7126/polaris/polaris/sep24/deposit.py#L387

The return value of make_memo may not be used.

**Comment by JakeUrban** [comment]
This is not bug, its called to ensure the memo is valid. `request.data.get("memo")` and `request.data.get("memo_type")` are both used later in the saved `Transaction` object.
