### ISSUE TITLE
Requirements conflict

### ISSUE THREAD

**Issue by nikita-gorodeckij** [stellar/django-polaris#556]
### What version are you using?

I try to install 2.0.5, 2.0.6 versions.

I use pipenv and when I do `pipenv lock` I got error:

```
ERROR: Could not find a version that matches async-timeout<5.0,==3.0.1,>=4.0.0a3 (from aiohttp==3.8.0->django-polaris==2.0.6->-r /var/folders/nf/w42zjb9x6ps07dfkbq7vnv0m0000gn/T/pipenv17zi1ztkrequirements/pipenv-o25ve7qi-constraints.txt (line 8))
Tried: 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 4.0.0, 4.0.0
Tried pre-versions: 4.0.0a0, 4.0.0a0, 4.0.0a1, 4.0.0a1, 4.0.0a2, 4.0.0a2, 4.0.0a3, 4.0.0a3
There are incompatible versions in the resolved dependencies:
  async-timeout<5.0,>=4.0.0a3 (from aiohttp==3.8.0->django-polaris==2.0.6->-r /var/folders/nf/w42zjb9x6ps07dfkbq7vnv0m0000gn/T/pipenv17zi1ztkrequirements/pipenv-o25ve7qi-constraints.txt (line 8))
  async-timeout==3.0.1 (from stellar-sdk==5.0.0->django-polaris==2.0.6->-r /var/folders/nf/w42zjb9x6ps07dfkbq7vnv0m0000gn/T/pipenv17zi1ztkrequirements/pipenv-o25ve7qi-constraints.txt (line 8))
```

Looks like polaris dependencies conflict with stellar sdk dependencies

**Comment by JakeUrban** [comment]
Thanks for catching this @nikita-gorodeckij, thankfully it looks like the packages are still installable.

@overcat, it look like the current version of `aiohttp` is incompatible with v5 of the `stellar-sdk` based on their shared `async-timeout` dependency. Can `stellar-sdk` bump the version of `async-timeout`?

**Comment by overcat** [comment]
Hi @JakeUrban, check https://github.com/StellarCN/py-stellar-base/releases/tag/5.0.1 please.

**Comment by JakeUrban** [comment]
Polaris 2.0.9 now includes the updated dependencies
