### ISSUE TITLE
ModuleNotFoundError: No Module named polaris.sep38

### ISSUE THREAD

**Issue by vahidid** [stellar/django-polaris#564]
### What version are you using?
django-polaris -> 2.1.0

### What did you do?
I set up my config thoroughly by tutorial and at the issue asset step, I got an error from the library.
I run the below command for issue asset on test net.
```
python app/manage.py testnet issue --asset=TEST
```

### What did you expect to see?
According to documents ``It should output a public and secret key for both the issuer and distribution account``

### What did you see instead?
But I got ModuleNotFoundError: No module named 'polaris.sep38'.

I took a look at the library code and in venv files, there is no sep38 module but be used in the package.

**Comment by JakeUrban** [comment]
Hi @vahidid, thanks for catching this. I forgot to add an `__init__.py` file to the sep38 directory which caused it to be ignored when packaging. I'll remove the 2.1 release and replace it with a patched version, 2.1.1.

**Comment by vahidid** [comment]
@JakeUrban 
I've done it for you :)

PR: https://github.com/stellar/django-polaris/pull/565
