### ISSUE TITLE
Handle 504 timeout errors from Horizon gracefully

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#571]
Currently, if Horizon returns a 504 response when Polaris submits a transaction, it is placed in the `error` status and is no longer processed by Polaris. This not good because the transaction could still be included in a ledger. If this happens, Polaris does not detect this and the transaction remains in the `error` status.

Instead, Polaris needs to have a sensible transaction submission and retry policy.

### Refactoring transaction processing

Polaris submits transactions in its `process_pending_deposits` CLI command, which queries for transactions in a few different states on startup and processes them. Transactions are either submitted or placed in one of the other states. Once all transactions have been processed, the command sleeps for the number of seconds specified by the `--interval` CLI argument, and then starts again, in a loop.

Because this command detects when transactions are or are not ready to be submitted and needs to update their external statuses appropriately, Polaris cannot attempt to submit transactions indefinitely until they are included in a ledger. As the command is implemented today, this would essentially block Polaris from making timely transaction status updates.

💡 We should refactor this command's logic such that detecting changes to a transaction's status is not blocked by attempting to submit transactions that are ready. This decoupling would allow Polaris to attempt to submit ready transactions indefinitely, simplifying error handling and retry logic.

This kind of system could be implemented using a mixture of `asyncio.Queue` objects and polling the database. When the process starts, the following tasks should execute concurrently:

- Task 1 (checking rails): Every `--interval` seconds, we should query for transactions whose funds _may_ have been delivered to the anchor and call `DepositIntegration.poll_pending_deposits()` so the anchor can return the transactions whose funds _have_ been delivered. For every transaction returned, we should place it in a "check account" queue.
- Task 2 (checking accounts): This task should be a function that reads from a queue indefinitely. For each transaction that comes in, it should check if the account exists.
    - If it doesn't:
        - If the distribution account requires multiple signatures, a transaction envelope should be constructed for creating the account, the transaction should be set to `pending_signatures`, and saved to the database.
        - If the distribution account does not require multiple signatures, it should be placed in the "submit transaction" queue.
    - If it does, but the appropriate trustline does not exist, the transaction's status should be updated to `pending_trust` and saved to the database.
    - If it does, and the account has the appropriate trustline, the transaction should be placed in the "submit transaction" queue
- Task 3 (checking signatures): Every `--interval` seconds, we should query for transactions that are no longer `pending_signatures` and place them in the "submit transactions" queue
- Task 4 (checking trustlines): Every `--interval` seconds, we should query for the transactions who are `pending_trust` and check if their trustlines exist
    - If the trustline exists:
        - If the distribution account requires multiple signatures, a transaction envelope should be created to make the deposit and saved to the transaction. It should be updated as `pending_signatures` and saved to the database.
        - If the distribution account does not require multiple signatures, it should be placed in the "submit transaction" queue.
- Task 5 (submitting transactions): This task should be a function that reads from the queue indefinitely. For each transaction that comes in, we should create the transaction envelope, save it to the transaction object, and submit it. On success:
    - If the transaction was for creating an account, its status should be updated to `pending_trust` and saved to the database
    - If the transaction was for making a payment, its status should be updated to `completed` and saved to the database

### Transaction submission logic

With the changes described in the section above implemented, we can implement the following transaction submission flow:

1. Query for transactions that were never taken out of the transaction submission queue in the previous invocation. If the anchor has changed the maximum fee they are willing to pay, we need to reconstruct these transactions with the new max fee.
    - If the distribution account requires multiple signatures, the transactions for that asset's distribution account should be placed in the "check signatures" queue
    - If the distribution account does not require multiple signatures, the transaction can be added to the "submit transaction" queue
2. Begin reading from the queue (which other tasks will add items to) and attempt to submit first the transaction
    - Because we can now attempt to submit a transaction indefinitely, we can use fairly large maximum time bounds (1 hour?, 24 hours?). We can also add an environment variable that makes this configurable.
    - If we get a success response, save the transaction as completed
    - If we get a 504 timeout, we should check if a SIGINT signal was sent to the process.
        - If no signal was sent, we should resumbit the transaction
        - If a signal was sent, we need to exit the task, saving all transactions in the queue to the database so they can be queried in the next invocation 
    - If we get a `tx_too_late` or `tx_insufficient_fee` error, we need to reconstruct the transaction with new timebounds.
        - If the transaction requires multiple signatures, we need to place it in the "checking signatures" queue
        - If the transaction does not require multiple signatures, we can place it back in the "submit transaction" queue
3. After each transaction succeeds or is placed in the "check signatures" queue, Polaris should check if a SIGINT was sent to the process. If one was, all transactions in the queue need to be saved to the database so they can be queried on the next invocation of the command. This actually goes for all queues.

**Comment by stfung77** [comment]
Diagrams for the transaction processing logic:
![image](https://user-images.githubusercontent.com/11511032/149004726-a08be5c6-86ee-4ce4-b3fc-a91eb4a0fa18.png)
![image](https://user-images.githubusercontent.com/11511032/149004746-079ae493-3aa0-4bdf-aba3-d3ed48ee0acb.png)
