### ISSUE TITLE
Sep31-send not work in polaris 2.1.2

### ISSUE THREAD

**Issue by kmpartner** [stellar/django-polaris#578]
### What version are you using?
2.1.2

### What did you do?
sep-31 send of test token by locally running anchor using docker-compose

### What did you expect to see?
finish sep-31 send

### What did you see instead?
stellar transaction takes place, but sep-31 send does not finish.
transaction's status not changed from pending_sender.

How can I solve this problem?

anchor's log keep displaying
server                           | 2021-12-26 18:11:12,096 - INFO: "GET /sep31/transactions/01713d79-7239-4af5-bb2b-100e0da324b3 HTTP/1.1" 200 532

trasaction object in network of  browser's developer tool
transaction: {id: "01713d79-7239-4af5-bb2b-100e0da324b3", status: "pending_sender", status_eta: null,…}
amount_fee: "0.01"
amount_in: "0.10"
amount_out: "0.09"
completed_at: null
external_transaction_id: null
id: "01713d79-7239-4af5-bb2b-100e0da324b3"
refunded: false
required_info_message: null
required_info_updates: null
started_at: "2021-12-27T02:05:00.959478Z"
status: "pending_sender"
status_eta: null
stellar_account_id: "GDMOBJX2QCDIZLYS5EKEJRUGL6H4SFFHC5PZ4X6CN2QTIUIGZGL4H2ND"
stellar_memo: "AAAAAAAAAAAAAAAAAAAAAAFxPXlyOUr1uysQDg2jJLM="
stellar_memo_type: "hash"
stellar_transaction_id: null
status_eta: null
stellar_account_id: "GDMOBJX2QCDIZLYS5EKEJRUGL6H4SFFHC5PZ4X6CN2QTIUIGZGL4H2ND"
stellar_memo: "AAAAAAAAAAAAAAAAAAAAAAFxPXlyOUr1uysQDg2jJLM="
stellar_memo_type: "hash"
stellar_transaction_id: null

**Comment by yuriescl** [comment]
@kmpartner Did you run `watch_transactions`? If yes, can you check if the logs contain any info about the Stellar transaction?

**Comment by kmpartner** [comment]
Thank you for your response.
After looking at logs of watch_transactions container. Only errors were shown.

I added environment variables in docker-compose.yaml file only in server container.

After adding variables to other containers in the YAML file, sep-31 send finished.
Thank you very much
