### ISSUE TITLE
Support SEP10 Multisig

### ISSUE THREAD

**Issue by tomerweller** [stellar/django-polaris#60]
https://github.com/stellar/stellar-protocol/pull/489

**Comment by leighmcculloch** [comment]
I'm working on a code implementation of what the protocol change will look like in our Go SDK. Recommend holding off on this until that is finished, to make sure we're all on the same page on what the change actually entails.

**Comment by overcat** [comment]
When stellar/stellar-protocol#489 is merged, I will implement it in Python SDK.

**Comment by JakeUrban** [comment]
@leighmcculloch is there an issue or open PR for the Go SDK change?

**Comment by leighmcculloch** [comment]
No not really. The SEP-10 change is still being iterated on. It likely won't be merged without a working Go SDK change to prove it out, and both will maybe merge together. There is also a PR open for the Go SDK change, but it is very likely to be re-iterated on and changed: stellar/go#2071.

**Comment by JakeUrban** [comment]
@leighmcculloch Regarding the following additional checks the server performs on the challenge transaction:
```
if the operation's source account exists:
- verify that client signatures count is one or more;
- verify that client signatures on the transaction are signers of the operation's source account;
- verify that client signatures are correct;
- verify that client signatures provide weight that meets the required threshold(s), if any;
if the operation's source account does not exist:
- verify that client signature count is one;
- verify that client signature is correct for the master key of the account address;
```

These additional requirements should really be implemented in the python SDK, specifically [verify_challenge_transaction()](https://stellar-sdk-zh-cn.readthedocs.io/en/latest/api.html#sep-0010-stellar-web-authentication). I'll make a pull request on the repository, but @overcat may not want to merge it until the SEP-10 PR is merged.

To test the SEP-10 changes then, we'd have to do one of the following:
- Test Polaris locally, running the forked python SDK
- Publish the forked python SDK publicly so we can actually deploy the changes
    - We could also deploy our own PyPI server instead, so we don't have to publish forks publicly
- Duplicate the changes made to the python SDK directly in Polaris
    - This would test the changes proposed to SEP-10 but it wouldn't reflect how it would actually be implemented in production

**Comment by leighmcculloch** [comment]
Oh, I missed we had upgraded to v2 of the Python SDK and that it now had the verification being done there. I thought it was still being done 100% in Polaris.

I agree we shouldn't expect the Python SDK to accept a PR for a change that hasn't been merged in the stellar-protocol repository.

I think going the route of your first suggestion makes the most sense, "Test Polaris locally, running the forked python SDK". That'll give us a final piece of confidence that the design fits an anchor implementing SEP-10. Once we get to that point I'll merge the SEP-10 PRs, and then we'll reach out to all SDKs to tell them about the new functions.

**Comment by ire-and-curses** [comment]
Yeah what I like to do is write a generic issue that can be fanned out to the SDKs, and if possible link to an existing implementation (e.g. the Go SDK) so people have something to use as a reference.

**Comment by JakeUrban** [comment]
PR: #107
