### ISSUE TITLE
New JWT model breaks wallet integration

### ISSUE THREAD

**Issue by ronaldoy** [stellar/django-polaris#61]
The new JWT model breaks interactive deposit/withdraw after the account did the first transaction. Mostly because of browser caching and lack of re-authentication. Common errors:
403 Session is not authenticated, 403 account for session not found.

**Comment by JakeUrban** [comment]
We've tested and deployed this to our heroku reference server, so it works at least in some cases. Which version are you running, 0.9.9 or 0.9.10? Are you using HTTPS? You have `PolarisSameSiteMiddleware` listed in `settings.MIDDLEWARE` _before_ `SessionMiddleware`?

This is what your session cookie should look like in chrome, see the `Set-Cookie` response header:
<img width="1319" alt="Screen Shot 2019-12-16 at 12 58 48 PM" src="https://user-images.githubusercontent.com/10968980/70942602-e0661a80-2003-11ea-9e57-3cbc092d8aa4.png">

If you could post a screenshot of the request and response headers for the `/webapp` request that would be helpful for diagnosing the problem.

**Comment by ronaldoy** [comment]
Jake,

We are running 0.9.10. Our settings.py middleware section is:

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "polaris.middleware.PolarisSameSiteMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

And the headers:





Note that this is a local environment, but in the main network it was running with HTTPS.

**Comment by ronaldoy** [comment]
It seems Safari related. To reproduce using SEP24 client:
1. Do all steps in Google Chrome - it will work.
2. Repeat in Safari with the same account - it will break
3. If you try with Firefox, it will work too.

**Comment by JakeUrban** [comment]
@ronaldoy when running in a local environment without HTTPS, session authentication will not work because 0.9.10 has a `Secure` flag added to the `sessionid` cookie. This `Secure` flag means that the cookie won't be sent in requests if it is not over HTTPS. This is probably at least 1 of the reasons you're having issues.

The good news is that the latest code (commits after 0.9.10 release) has an improved development environment. You can run a local polaris server with HTTPS using the `docker-compose.dev.yml` file.

```
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml up
```

This will run a HTTPS server locally. You'll be able to edit the code and have your changes immediately reflected in the server.

Can you try running the HTTPS server and let me know if you still have issues? I'm going to try using Safari right now.

**Comment by JakeUrban** [comment]
I can confirm that the current code does not work with Safari, even when using HTTPS. I found the reason why too, see [this help page](https://support.apple.com/guide/safari/prevent-cross-site-tracking-sfri40732/mac). The key quote:

> Unless you visit and interact with the third-party content provider as a first-party website, their cookies and website data are deleted.

This setting can be turned off by going to `Safari Preferences -> Privacy -> Prevent cross-site tracking`

However, we don't want to require users to go into Safari Preferences for this to work for them. I'm looking into possible solutions and will update this thread with my findings.

**Comment by msfeldstein** [comment]
I think we should move the demo client, and the advisory in the sep, away from using iframes.  The web as  a platform is aggressively pushing back against 3rd party cookies.  I don't necessarily think these are 'third party cookies' as such, but it may be going against platform best practices

**Comment by msfeldstein** [comment]
and by away from iframes i mean using popups, similar to oauth login

**Comment by msfeldstein** [comment]
https://github.com/stellar/sep24-demo-client/issues/147

**Comment by JakeUrban** [comment]
@ronaldoy once we change the demo client to start serving the interactive flow through a popup/webview, all these cross-site issues should go away.

**Comment by JakeUrban** [comment]
@ronaldoy The changes to the demo client have been deployed, can you confirm there are no authentication issues and that we can close this ticket?

**Comment by ronaldoy** [comment]
Authentication problems solved!
