### ISSUE TITLE
`process_pending_deposits` uses Unix-specific python standard library functions

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#613]
Polaris uses the [`loop.add_signal_handler()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio-event-loop) function, which is a unix-specific function since Windows does not have signals.

Running `process_pending_deposits` on a windows machine will result in an immediate crash of the program with a `NotImplementedError`.

We need to refactor the graceful cleanup logic to use os-agnostic functionality. cc @stfung77

**Comment by Unique-coder** [comment]
Thanks for taking it up @stfung77

**Comment by stfung77** [comment]
@Unique-coder would you mind testing the change in this PR (https://github.com/stellar/django-polaris/pull/615)? None of us have a windows setup handy to test this out.

**Comment by Unique-coder** [comment]
Alright @stfung77. I will test it out get back to you

**Comment by stfung77** [comment]
Hey @Unique-coder, did you get a change to test this out? we're trying to release in the next day or two so let us know if you don't have the bandwidth to test this. thanks!

**Comment by stfung77** [comment]
tested #615 on windows and its working
