### ISSUE TITLE
Network passphrase is necessary

### ISSUE THREAD

**Issue by nikita-gorodeckij** [stellar/django-polaris#637]
https://github.com/stellar/django-polaris/blob/73f4bbe7f874f67ad3f6d6476c64feb2f6dd3c83/polaris/management/commands/process_pending_deposits.py#L711

This line fails because network_passphrase if necessary arg for TransactionEnvelope.from_xdr method

**Comment by nikita-gorodeckij** [comment]
This line made broken all deposits for client with claimable balance support. Please fix it ASAP.

**Comment by JakeUrban** [comment]
Hi @nikita-gorodeckij, version 2.3.1 has been released with a patch. Thanks for pointing this out.
