### ISSUE TITLE
ENABLE_SEP_0023="true" missing on documentation

### ISSUE THREAD

**Issue by ajuricabense** [stellar/django-polaris#644]
### What version are you using?
2.3.1

### What did you do?
The documentation of version 2.3.1 of the environmental variables did not specify to add: ENABLE_SEP_0023="true", which raises the error:

File "/home/alfredo/MEGA_c/2021_2022/Alpaca/stellar/virtualenv/lib/python3.8/site-packages/polaris/apps.py", line 66, in check_sep23_supported
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: environment variable ENABLE_SEP_0023 must be set to 'true'

Please add in the documentation the complete lines:
ACTIVE_SEPS=
HOST_URL=http://localhost:8000
LOCAL_MODE=1
ENABLE_SEP_0023="true"

**Comment by JakeUrban** [comment]
Actually, this check was removed in v2.3, are you sure you're using the latest version?

**Comment by JakeUrban** [comment]
https://github.com/stellar/django-polaris/pull/617

**Comment by ajuricabense** [comment]
@JakeUrban How can I check the version I am using? to be sure.

**Comment by JakeUrban** [comment]
It should be in your requirements lock file like `poetry.lock` or `pipenv.lock`, or just `requirements.txt`

**Comment by ajuricabense** [comment]
@JakeUrban You are correct, I made a mistake, my version is django-polaris==2.2.0

**Comment by JakeUrban** [comment]
No problem! I'll close the issue.
