### ISSUE TITLE
Never send incoming payment to stellar network

### ISSUE THREAD

**Issue by yanielbf** [stellar/django-polaris#659]
### What version are you using?

I am using the las version of polaris 2.3.4

### What did you do?

I am implementing an anchor using django-polaris. I have followed the documentation which indicates. I'm using the demo-wallet to test the anchor and it creates the transaction for me but leaves it in the "pending_user_transfer_start" state. I am executing the command "python app/manage.py process_pending_deposits" and it detects that my transactions have already been completed by the off-chain but they are not sent to Stellar.
I found this same problem in this post. (https://stellar.stackexchange.com/questions/6027/django-polaris-not-processing-pending-deposits)

**My asset (GALAR)**
https://stellar.expert/explorer/testnet/asset/GALAR-GDBOS6SXMT4JPPUTJMVKG7PVOQ56JEH5UI64TFBCZKYORA5TJA3IENSB

**My Issuer**
GDBOS6SXMT4JPPUTJMVKG7PVOQ56JEH5UI64TFBCZKYORA5TJA3IENSB
SCOVNYCUCQKUDJFFFZXWP43O7EPBXEXA2KR52HGRYYPKKWHWY36PIXDF

**My Distributor**
GDP4KCNXMNHV2RC52Y77C23AN5SQNZWKXQKHBYLV3KJJHANS4376RYNS
SCY7EXKRPXVU4TCRS5A25YYZ3UUSK6LO773ZAXSLJ6NTSG4EPZYKL7U3

**Image from demo-wallet**
![Screen Shot 2022-10-10 at 07 33 27](https://user-images.githubusercontent.com/11427255/194847167-e5241a15-44ec-4f96-b996-3ddb76958c4a.png)

**Transaction in my database**
"polaris_transaction": [
	{
		"id" : "a953d104324846f0b4b2f3f7fbd53157",
		"paging_token" : null,
		"stellar_account" : "GBVUYMNUVFRCFBWSE3FBJQDU4ZOSAG7QQJOL5UIJY6TOYWFNOXCSR5FZ",
		"kind" : "deposit",
		"status" : "pending_user_transfer_start",
		"status_eta" : null,
		"status_message" : null,
		"stellar_transaction_id" : null,
		"external_transaction_id" : null,
		"amount_in" : 100,
		"amount_out" : 95,
		"amount_fee" : 5,
		"started_at" : "2022-10-10 10:15:15.510487",
		"completed_at" : null,
		"from_address" : null,
		"to_address" : "GBVUYMNUVFRCFBWSE3FBJQDU4ZOSAG7QQJOL5UIJY6TOYWFNOXCSR5FZ",
		"required_info_updates" : null,
		"required_info_message" : null,
		"memo" : null,
		"memo_type" : "hash",
		"receiving_anchor_account" : null,
		"refunded" : 0,
		"protocol" : "sep24",
		"asset_id" : 1,
		"envelope_xdr" : null,
		"pending_signatures" : 0,
		"channel_seed" : null,
		"claimable_balance_id" : null,
		"claimable_balance_supported" : 0,
		"more_info_url" : "http:\/\/localhost:8000\/sep24\/transaction\/more_info?id=a953d104-3248-46f0-b4b2-f3f7fbd53157",
		"on_change_callback" : null,
		"pending_execution_attempt" : 0,
		"client_domain" : "demo-wallet-server.stellar.org",
		"amount_expected" : 100,
		"account_memo" : null,
		"muxed_account" : null,
		"fee_asset" : null,
		"quote_id" : null,
		"queue" : null,
		"queued_at" : null,
		"submission_status" : "not_ready"
	}
]}

**Integration rail:**
def poll_pending_deposits(self, pending_deposits: QuerySet, *args: List, **kwargs: Dict):
        received_payments = []
        for transaction in pending_deposits:
            received_payments.append(transaction)
        return received_payments

### What did you expect to see?

Send the transaction to Stellar Network and reflect the change in my db

### What did you see instead?

Keep same status_submition not_ready and status pending_user_transfer_start

**Comment by JakeUrban** [comment]
Hey @yanielbf, are you still running into this issue? Can you provide the logs of the `proces_pending_deposits` process?

**Comment by yanielbf** [comment]
@JakeUrban Hi Jake, I solved my problem. I'm working right now on implementing an anchor for my app. Maybe in the future I will communicate with you. Greetings
