### ISSUE TITLE
Migrate to Python 3.11

### ISSUE THREAD

**Issue by antb123** [stellar/django-polaris#670]
### What problem does your feature solve?

Performance is significantly better.

### What would you like to see?

Migrate to Python 3.11+

### What alternatives are there?

Postpone...

**Comment by JakeUrban** [comment]
Hey @antb123, I don't think we can require everyone to migrate to 3.11 or higher, given that Python 3.7 is still actively maintained. The Python Stellar SDK takes the same approach.

You should still be able to run Polaris with 3.11 in your own project though, right?
