### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by estar-app** [stellar/django-polaris#671]
### What did you expect to see?

I followed the tutorial on the documentation, but the front end isn't displaying while the pah to the admin and /.well-known/stellar.toml is resolving. The following is the urlconfig:

from django.contrib import admin
from django.urls import path, include

import polaris.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(polaris.urls)),
]

What else should be done to display the users interface?

https://naturepay.gf4n.xyz/

https://naturepay.gf4n.xyz/.well-known/stellar.toml

https://naturepay.gf4n.xyz/admin/

**Comment by JakeUrban** [comment]
There is no UI at the root endpoint. Polaris provides a URL for the UI to the wallet after it initiates a transaction. You can experiment more by using testanchor.stellar.org & demo-wallet.stellar.org.
