### ISSUE TITLE
MIssing SEP9 KYC/AML Fields (bank_account_type) from SEP_9_FIELDS utils.py

### ISSUE THREAD

**Issue by santoshchaurasiya** [stellar/django-polaris#677]
### What version are you using?
`2.3.6`

### What did you do?
Implementing SEP-12 customer KYC.

### What did you expect to see?

I should expect to see the` bank_account_type` in defined SEP_9_FIELDS .

### What did you see instead?
Missing the above two fields from there.

Actually, `bank_account_type` are the SEP9 KYC/AML Fields but these are not present in below utils.py file.
defined.
https://github.com/stellar/django-polaris/blob/v2.3.6/polaris/utils.py#L207a

Here is the reference, we can see that, those fields are already defined in SEP9 fields.
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0009.md#natural-person-kyc-fields

**Comment by JakeUrban** [comment]
resolved via #679
