### ISSUE TITLE
MIssing OPERATION_SEND constant from polaris settings.py file.

### ISSUE THREAD

**Issue by santoshchaurasiya** [stellar/django-polaris#678]
### What version are you using?

`2.3.6`

### What did you do?

`Implementing SEP-31`

### What did you expect to see?
I am expecting to see `OPERATION_SEND` constant should be defined in below file.
https://github.com/stellar/django-polaris/blob/master/polaris/settings.py#L139

### What did you see instead?
Missing the `OPERATION_SEND`  constant from there.

**Comment by JakeUrban** [comment]
resolves with #680
