### ISSUE TITLE
Needs NETWORK_PASSPHRASE in toml

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#71]
SEP1 specifies a NETWORK_PASSPHRASE toml entry to tell clients what network this domain is operating off of.  We should add it and make it configurable, at least to testnet/pubnet
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md#account-information

**Comment by JakeUrban** [comment]
Will do.

Also, there are a bunch of fields that could be specified in the TOML. Should we add `ACCOUNTS`, `VERSION`, `WEB_AUTH_ENDPOINT`, etc.?
