### ISSUE TITLE
Feature Request: Add significant decimal places column to Asset model

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#94]
For the US dollar and most other fiat currencies, there are only 2 significant decimal places. But for cyrpto assets, there could be a large number of significant decimal places. We'll allow the anchor to specify how many decimal places should be reserved, with a maximum of 7.

**Comment by tomerweller** [comment]
Why 25? Stellar supports up to 7

**Comment by JakeUrban** [comment]
No reason, I just wasn't aware of the limit. We can do 7.
