### ISSUE TITLE
Feature Request: Insert arbitrary javascript into rendered templates

### ISSUE THREAD

**Issue by JakeUrban** [stellar/django-polaris#98]
Anchors may way to use Google Analytics or another tool that requires them to add a script to the web pages served from their anchor server. 

Polaris doesn't allow anchors to modify the templates themselves, but we can provide an integration point for them to return strings of javascript that will be inserted into the page.

An open question is whether or not to provide the integration function a parameter that allows anchors to differentiate between pages. Will anchors want different scripts for different pages, or will they simply want 1 or more scripts on all pages?

**Comment by JakeUrban** [comment]
@msfeldstein what do you think of the question posed at the end of the description?

**Comment by msfeldstein** [comment]
I think not doing that is fine for a v1.  There's no need to design anything more complicated until we have someone actually requesting it.

**Comment by msfeldstein** [comment]
80% of the value of analytics comes from just dropping a static tag on all pages
